---
title: "Manuscript Outline"
author: "Spiro Stilianoudakis"
date: "September 11, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

   + Paragraph 1:
      - What are TADs and what role do they play in the human genome?
      - Why do we care about TADs?
      
   + Paragraph 2:
      - What is in the current literature?
      
   + Paragraph 3:
      - What are the issues?
      - Why are they issues?
      
   + Paragraph 4:
      - What are the current methods out there?
      - What drawbacks do they have?
    
   + Paragraph 5:
      - Defined the problem
      - What have we done?
      - Why have we done it?
      
# Methods 

* The Data
   + Paragraph 1:
      - Where was the data obtained?
   + Paragraph 2:
      - How it was used?
      - How was the response vector created
      
* Genomic Annotations
   + Paragraph 1: 
      - Where was the annotation data obtained?
      - How were they used?

* Data Pipeline:
   + What was the pipeline used for?
   + Set up structure of pipeline
   + How were techniques evaluated?
   
* Normalization:
   + What techniques were used/compared?
   + How were they used/how do they worked?
   
* Class Imbalance:
   + What techniques were used/compared?
   + How were they used/how do they worked?
   
* Variable Selection:
   + What techniques were used/compared?
   + How were they used/how do they worked?

* Final Model:
   + What model(s) we used to evaluat the pipeline processed data
   + How the model(s) were performed
   + What we compared our models to
   
# Results
   
* GM12878 Resuts
   + How many total genomic bins
   + How many total TADs
      - Summary stats for lengths of TADs
   + Total number of features 
      - Summary stats for both counts and distance features
      - Which features were removed for near zero variance
   + Normalization Techniques
   + Class balancing techniques
   + Variable selection techniques
   + Final Models
      - Mourad Models (MLR & LASSO)
      - Models using distance/counts features with out pipeline (MLR & LASSO)
      - Elastic-Net using processed data
      - Comparisons
* Validate results using K562 cell line
* Validate results using TFBS cell line

# Discussion

* State the results that were interesting 
   - Specific to each cell line/tfbs
   - Then results all together
* State how much better models using our pipeline performed compared to Mourad
   - Was it due to the model choice or the use of distance features?
* Limitations/Future
   - Mention the need for HiC experiments using higher resolutions
   - Experimenting with TAD data using other methods
   - Exploring other cell lines


