---
output:
  word_document:
    reference_docx: ../Manuscript/styles.doc/NSF_grant_style.docx
  html_document: default
  pdf_document: default
---

To the Editor of the "Regulatory Elements" special issue

Dear Dr. Sands,

We are submitting our manuscript "preciseTAD: A machine learning framework for precise 3D domain boundary prediction at base-level resolution" to be considered for the special issue "Regulatory Elements" in _Genome Biology_. This manuscript will be of interest to the community studying the regulatory associations with the three-dimensional (3D) genome structure.

Our manuscript is submitted under the "Software" category. The main highlights of our software are:

- A Bioconductor R package *preciseTAD* implementing a comprehensive machine learning framework for predicting boundaries of 3D domains (topologically associating domains (TADs), chromatin loops) using one-dimensional (1D) regulatory genomic annotation data (e.g., ChIP-seq from ENCODE).

- *preciseTAD* can be used to refine the location of domain boundaries and identify de novo boundaries missed by conventional TAD/loop callers.

- *preciseTAD* prioritizes regulatory elements associated with domain boundaries. Trained on any 3D features (e.g., besides TAD/loop boundaries, regions of A/B compartment switching, frequently interacting regions (FIREs), differentially interacting chromatin regions, etc.), *preciseTAD* defines (epi)genomic signatures most predictive of those features.

- The pre-trained models provided with the package can predict domain boundaries in cells without Hi-C data using only genomic annotation data.

The main findings of our work are:

- Transcription factors, spatial relationships (distance within the linear genome) between them and boundaries, random under-sampling are the critical considerations needed for accurate boundary predictions.

- Only four transcription factors, CTCF, RAD21, SMC3, ZNF143, are sufficient for domain boundary predictions.

- Boundaries of TADs and loops are associated with the same regulatory signatures, suggesting similar mechanisms of their formation.

- Biological properties of boundaries predicted using *preciseTAD* include the highest genomic signal of CTCF and other transcription factors, closer proximity to other genomic signatures, and higher` conservation across cell lines.

- We provide genomic coordinates of the predicted TAD/loop boundaries for GM12878 and K562 cell lines.


In summary, our systematic machine learning framework evaluates previously overlooked properties of 3D and 1D data associations, linking them into the most optimal model for domain boundary predictions. This improved precision in the domain boundary location will provide deeper insight into the association between genomic regulators and the 3D genome organization.

The *preciseTAD* R package is available on Bioconductor, https://bioconductor.org/packages/preciseTAD. Its source code is freely available on GitHub https://dozmorovlab.github.io/preciseTAD/. All data needed to reproduce our results are available from public repositories and publications. We also want to assure that this manuscript is not being considered for publication elsewhere.

With our best regards,  

Mikhail Dozmorov, Ph.D., Blick scholar  
Associate Professor,  Department of Biostatistics  
Affiliate, Department of Pathology  
Virginia Commonwealth University  
One Capitol Square, room 738  
830 East Main Street  
Richmond,  Virginia  23298  
e-mail:  mikhail.dozmorov@vcuhealth.org  
Phone: 804-827-2055  

09/30/2020