---
title: "Legends for supplementary material"
output: pdf_document
---

**Supplementary Table 4. Hi-C data.** A complete list of the Hi-C data libraries used to obtain the locations of topologically associating domains.

**Supplementary Figure 14. Number of TADs called throughout the genome.** TADs were called throughout each of the 22 autosomal chromosomes for cell lines GM12878 (red) and K562 (blue) using the Arrowhead algorithm [@durand2016juicebox], across each data resolution including 10 kb, 25 kb, 50 kb, and 100 kb (A-D) respectively. 

**Supplementary Table 8. Summary statistics for TAD lengths.** The following summary statistics were recorded regarding lengths of TADs that were called and delineated into TAD boundaries including the minimum, 1st quartile, median, mean, 3rd quartile, and maximum TAD lengths (in basepairs). The summaries are provided for each cell line, resolution, and within each chromosome. [???should I leave space for 9th chromosome on k562 where no TADs were called?]

**Supplementary Table 2. Genomic annotations.** A complete list of the genomic annotations used to build the feature space for all downstream models. The GRCh37/hg19 human genome assembly was used. "Genomic Class" - broad category of genomic features, "Element" - names of genomic features, "Available Cell Type" - the name of the cell type in which the annotation was available, "Cell Type-Specific Source" - download URL specific to the cell line (not all annotations were provided by the same institutions). 

**Supplementary Figure 1. Distance densities from centers of genomic bins to closest annotation.** Density curves of the distances (in millions of base pairs) from the center of genomic bins to the center of the nearest respective annotation for the GM12878 (left column) and K562 (right column) cell lines respectively. Each curve represents the raw (red) and $log_{2}$ transformed (blue) distance profiles for each annotation, across each of the 4 resolutions (A-D).

**Supplementary Figure 2. Clustered correlogram for genomic annotations at the 10 kb resolution for the GM12878 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Figure 3. Clustered correlogram for genomic annotations at the 10 kb resolution for the K562 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Figure 4. Clustered correlogram for genomic annotations at the 25 kb resolution for GM12878 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Figure 5. Clustered correlogram for genomic annotations at the 25 kb resolution for the K562 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Figure 6. Clustered correlogram for genomic annotations at the 50 kb resolution for GM12878 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Figure 7. Clustered correlogram for genomic annotations at the 50 kb resolution for the K562 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Figure 8. Clustered correlogram for genomic annotations at the 100 kb resolution for GM12878 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Figure 9. Clustered correlogram for genomic annotations at the 100 kb resolution for the K562 cell line.** Pairwise correlations between the total number of instances where regions defined by genomic annotations overlapped with flanked TAD boundaries on the linear genome. Positive correlations are denoted in red, while negative correlations are denoted in blue. The upper triangular matrix of correlations was clustered using Ward's method. Delineated regions of high correlations indicate genomic annotations that are colocalized at TAD boundaries.

**Supplementary Table 7. Optimal alpha and lambda penalization parameters.** The tuned alpha and lambda penalization parameter terms after performing 10-fold cross validated elastic-net regularization specific to cell line, resolution, re-sampling technique, and predictor type.

**Supplementary Figure 10. Comparing ensemble system specific model performances for K562.** Performances of random forest classification models built on each of the 3 predictor types: OC (A), OP (B), and Distance (C). Within each predictor type, and across resolution, F1-Scores and MCCs metrics were recorded for models subsequently implemented on re-sampled data using the 4 re-sampling techniques: None (red), ROS (green), RUS (blue), and SMOTE (purple).

**Supplementary Table 4. Ranking predictive importance between predictor types for annotation-specific models for GM12878.** Annotation-specific random forest classification models were implemented on SMOTE resampled data, across resolution. Each model contained each of the 3 predictor types for one genomic annotation. Predictive importance was rescaled to values between 0 and 100. The predictor type with importance value of 100 indicates it was the most informative predictor type out of the 3.

**Supplementary Table 5. Ranking predictive importance between predictor types for annotation-specific models for K562.** Annotation-specific random forest classification models were implemented on SMOTE resampled data, across resolution. Each model contained each of the 3 predictor types for one genomic annotation. Predictive importance was rescaled to values between 0 and 100. The predictor type with importance value of 100 indicates it was the most informative predictor type out of the 3.

**Supplementary Figure 15. Predictive importance of genomic annotations for random forest models implemented on SMOTE resampled data with distance-type predictors for K562.** Importance was rescaled to values between 0 and 100, and discretized. The importance was subsequently sorted according to the most predictive annotations associated with the 10 kb resolution. Annotations with higher values of predictive importance are denoted in dark red, while annotations that were regularized in the pipeline for specific resolutions are denoted in grey.

**Supplementary Figure 11. Comparing category-specific random forest models implemented on SMOTE re-sampled data with distance-type predictors for K562.** Performances, separated by F1-Score and MCC, were compared for models using specific categories of annotations as the feature space including: histone modifications (red), chromatin state segmentations (green), transcription factor binding sites, and a feature space containing all 3 types combined (purple). 

**Supplementary Figure 12. Comparing $log_{2}$ distance profiles of top predictive transcription factor binding sites by bin class for 25 kb resolution, on GM12878.** Violin plots (top) and plots of differences in quantiles (bottom) between genomic bin class for 4 of the top predictive TFBS determined by the best performing model, including: SMC3 (A), ZNF143 (B), CTCF (C), and RAD21 (D). For the plots of differences in quantiles, the reference group are the genomic bins that did not overlap with a flanked TAD boundary. That is, quantile differences above 0 indicate that bins that overlapped with flanked TAD boundaries exhibited smaller quantiles.

**Supplementary Figure 13. Comparing $log_{2}$ distance profiles of top predictive transcription factor binding sites by bin class for 50 kb resolution, on GM12878.** Violin plots (top) and plots of differences in quantiles (bottom) between genomic bin class for 4 of the top predictive TFBS determined by the best performing model, including: SMC3 (A), ZNF143 (B), CTCF (C), and RAD21 (D). For the plots of differences in quantiles, the reference group are the genomic bins that did not overlap with a flanked TAD boundary. That is, quantile differences above 0 indicate that bins that overlapped with flanked TAD boundaries exhibited smaller quantiles.

**Supplementary Figure 14. Comparing $log_{2}$ distance profiles of top predictive transcription factor binding sites by bin class for 100 kb resolution, on GM12878.** Violin plots (top) and plots of differences in quantiles (bottom) between genomic bin class for 4 of the top predictive TFBS determined by the best performing model, including: SMC3 (A), ZNF143 (B), CTCF (C), and RAD21 (D). For the plots of differences in quantiles, the reference group are the genomic bins that did not overlap with a flanked TAD boundary. That is, quantile differences above 0 indicate that bins that overlapped with flanked TAD boundaries exhibited smaller quantiles.

**Supplementary Figure 15. Comparing $log_{2}$ distance profiles of top predictive transcription factor binding sites by bin class for 10 kb resolution, on K562.** Violin plots (top) and plots of differences in quantiles (bottom) between genomic bin class for 4 of the top predictive TFBS determined by the best performing model, including: SMC3 (A), ZNF143 (B), CTCF (C), and RAD21 (D). For the plots of differences in quantiles, the reference group are the genomic bins that did not overlap with a flanked TAD boundary. That is, quantile differences above 0 indicate that bins that overlapped with flanked TAD boundaries exhibited smaller quantiles.

**Supplementary Figure 16. Comparing $log_{2}$ distance profiles of top predictive transcription factor binding sites by bin class for 25 kb resolution, on K562.** Violin plots (top) and plots of differences in quantiles (bottom) between genomic bin class for 4 of the top predictive TFBS determined by the best performing model, including: SMC3 (A), ZNF143 (B), CTCF (C), and RAD21 (D). For the plots of differences in quantiles, the reference group are the genomic bins that did not overlap with a flanked TAD boundary. That is, quantile differences above 0 indicate that bins that overlapped with flanked TAD boundaries exhibited smaller quantiles.

**Supplementary Figure 17. Comparing $log_{2}$ distance profiles of top predictive transcription factor binding sites by bin class for 50 kb resolution, on K562.** Violin plots (top) and plots of differences in quantiles (bottom) between genomic bin class for 4 of the top predictive TFBS determined by the best performing model, including: SMC3 (A), ZNF143 (B), CTCF (C), and RAD21 (D). For the plots of differences in quantiles, the reference group are the genomic bins that did not overlap with a flanked TAD boundary. That is, quantile differences above 0 indicate that bins that overlapped with flanked TAD boundaries exhibited smaller quantiles.

**Supplementary Figure 18. Comparing $log_{2}$ distance profiles of top predictive transcription factor binding sites by bin class for 100 kb resolution, on K562.** Violin plots (top) and plots of differences in quantiles (bottom) between genomic bin class for 4 of the top predictive TFBS determined by the best performing model, including: SMC3 (A), ZNF143 (B), CTCF (C), and RAD21 (D). For the plots of differences in quantiles, the reference group are the genomic bins that did not overlap with a flanked TAD boundary. That is, quantile differences above 0 indicate that bins that overlapped with flanked TAD boundaries exhibited smaller quantiles.


<!--
**Supplementary Table 5. Data Summaries and Imbalance Ratios.** The total number of genomic bins included in the complete, training, and testing sets, as well as the subsequent imbalance ratios across resolutions and cell lines. Imbalance ratio is defined as the ratio of genomic bins that overlapped a flanked TAD boundary (minority class), divided by the number of genomic bins that did not overlap a flanked TAD boundary (majority class).
-->

<!--
**Supplementary Figure 2. Correlations between genomic annotations across cell lines and resolutions.** Upper and lower correlation heatmaps between genomic annotations for the GM12878 (A-D) and K562 (E-H) cell lines, across the 10 kb, 25 kb, 50 kb, and 100 kb resolutions (A, B, C, D; and E, F, G, H respectively). The correlations were evaluated on the total number of overlapped bases between flanked TAD boundaries and genomic annotations. High correlations (red) denote annotations that tended to occur colocally near TAD boundaries. Low correlations (blue) denote annotations that did not tend to occur near TAD boundaries together.

**Supplementary Figure 2A. Correlograms separated by genomic annotation category for overlap count predictor types, using 10 kb resolution data, on the GM12878 cell line** 
-->

<!--
**Supplementary Figrue 12. Barplots comparing model performance for each predictor type across 25 kb, 50 kb, and 100 kb data resolutions** Model performances were evaluated using F1-scores, MCCs, and balanced accuracies for each of the 4 resampling techniques, across both the GM12878 (A-C) and K562 (D-F) cell lines. Missing bars indicate that the model was unable to correctly predict any genomic regions that overlapped with flanked TAD boundaries in the test data, resulting in zero true positives. Bars that appear in the opposite direction (for MCC) indicate a negative correlation between the observed and predicted binary classifications of flanked TAD boundaries.

**Supplementary Figure 13. Line plots comparing models using the remaining resampling techniques with distance-type predictors.** Model performances were evaluated using F1-score, MCC, and balanced accuracy for each of the 4 data resolutions, across both the GM12878 (red, solid line) and K562 (blue; dashed line) cell lines. For a given metric, each point represents a model applied to a particular resolution with distance type predictors for the feature space, after which a particular resampling technique was used to create balanced classes on the trianing set, including none (A), random over-sampling (B), and random under-sampling (C).

**Supplementary Figure 14A. Variable importance of the top 20 most predictive genomic annotations for models using no resampling technique with distance-type predictors.** The list of genomic features are the union of the top 20 most important genomic annotations across resolutions for the GM12878 (A) and K562 (B) cell lines. Variable importance is assigned on a continuous scale (range: 0-100). Grid entries filled in gray denote an annotation that was not featured as one of the top 20 most predictive variables in a given model. The genomic annotations are sorted by highest level of importance obtained from a random forest model with distance-type predictors at the 10 kb data resolution, while not performing a class balancing technique, for each cell line respectively.

**Supplementary Figure 14B. Variable importance of the top 20 most predictive genomic annotations for models using random over-sampling with distance-type predictors.** The list of genomic features are the union of the top 20 most important genomic annotations across resolutions for the GM12878 (A) and K562 (B) cell lines. Variable importance is assigned on a continuous scale (range: 0-100). Grid entries filled in gray denote an annotation that was not featured as one of the top 20 most predictive variables in a given model. The genomic annotations are sorted by highest level of importance obtained from a random forest model using distance-type predictors at the 10 kb data resolution, while using random over-sampling to create balanced classes, for each cell line respectively.

**Supplementary Figure 14C. Variable importance of the top 20 most predictive genomic annotations for models using random under-sampling with distance-type predictors.** The list of genomic features are the union of the top 20 most important genomic annotations across resolutions for the GM12878 (A) and K562 (B) cell lines. Variable importance is assigned on a continuous scale (range: 0-100). Grid entries filled in gray denote an annotation that was not featured as one of the top 20 most predictive variables in a given model. The genomic annotations are sorted by highest level of importance obtained from a random forest model using distance-type predictors at the 10 kb data resolution, while using random under-sampling to create balanced classes, for each cell line respectively.
-->


<!--
**Supplementary Figures 9-23. Precision-Recall curves for 25 kb, 50kb, and 100kb data.** Precision-recall curves were used to initially compare performance of random forest models with different predictor types on 25 kb, 50kb, and 100kb resolution data, across each resampling technique. GM12878 (solid line) and K562 (dashed line) cell lines were compared with predictor type-specific models which included overlap counts (blue), overlap percents (purple), log distance (green), and all three combined (red). 
-->

<!--
**Supplementary Table 2. Area under Precision-Recall Curves.** Comparison of models applied to different data resolutions, resampling techniques, and predictor types for each of the two cell lines in terms of AUPRC. The column labeled "All" denotes models with all 3 combined predictor types.
-->

<!--
**Figure 3. Recursive Feature Elimination for 25 kb, 50 kb, and 100 kb data** Beginning with the full set of distance type predictors for each cell line, models built on 25 kb, 50 kb, and 100 kb resolution data were recursively evaluated at different subsets of feature size. For convenience and computational efficiency, feature size decreasing in powers of 2 was considered. The maximum size for feature subsets differed between cell line due the available annotations that were considered and provided in Supplementary Table 1. Near optimal performance was achieved using the top 32 distance type predictors for both the GM12878 (red) and K562 cell lines (blue).
-->
 


