---
title: "Creating Table of Data Summaries"
author: "Spiro Stilianoudakis"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages and functions

```{r}
library(S4Vectors)
library(GenomicRanges)
library(ggplot2)
library(caret)
library(randomForest)
library(glmnet)
library(gbm)
library(DMwR)
library(rtracklayer)
library(Biostrings)
library(BSgenome)
library(cluster)
library(pROC)
library(SuperLearner)
library(data.table)
library(PRROC)
library(bigmemory)
library(ranger)
library(dplyr)
library(parallel)
library(doSNOW)
library(foreach)
library(pbapply)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)
library(GenometriCorr)
library(ggsignif)
library(Vennerable)
library(VennDiagram)
library(ChIPpeakAnno)
library(EnrichedHeatmap)

source("Z:/TAD_data_analysis/functions_for_R_package/preciseTAD.R")
source("Z:/TAD_data_analysis/functions_for_R_package/TADRF.R")
source("Z:/TAD_data_analysis/functions_for_R_package/TADrfe.R")
source("Z:/TAD_data_analysis/functions_for_R_package/distance_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/percent_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/count_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/binary_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/signal_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/annots_to_granges_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/extract_boundaries_func.R")

```

## Creating seqdata

```{r}

getChrLength <- function(genome = "BSgenome.Hsapiens.UCSC.hg19"){
  g <- getBSgenome(genome, masked=FALSE)
  data.frame(chrom=1:24, length=seqlengths(g)[1:24])
}
.chrAsNum <- function(tbl){
  tbl$chrom <- gsub("chr", "", tbl$chrom)
  tbl$chrom[tbl$chrom=="X"] <- 23
  tbl$chrom[tbl$chrom=="Y"] <- 24
  tbl$chrom <- as.numeric(tbl$chrom)
  tbl[order(tbl$chrom),]
}
getCentromeres <- function( genome="hg19" ){
  mySession <- try(browserSession("UCSC"), silent=TRUE)
  # In case of failure, try another mirror
  if(inherits(mySession, "try-error"))
    mySession <- browserSession("UCSC",
                                url="http://genome-euro.ucsc.edu/cgi-bin/")
  genome(mySession) <- genome
  obj <- ucscTableQuery(mySession, table="gap")
  tbl <- getTable(obj)
  tbl <- tbl[tbl$type=="centromere", c("chrom", "chromStart", "chromEnd")]
  colnames(tbl)[2:3] <- c("centromerStart", "centromerEnd")
  .chrAsNum(tbl)
}
makeHg19 <- function(){
  tbl <- merge(getChrLength(), getCentromeres(), by="chrom")
  cumlen <- c(0, cumsum(as.numeric(tbl$length))[-nrow(tbl)])
  cbind.data.frame(tbl, cumlen=cumlen)    
}
hg19 <- makeHg19()
hg19$chrom <- paste0("CHR",hg19$chrom)

seqLength <- hg19$length[hg19$chrom %in% CHR]
seqDataList <- list()
for(k in 1:length(seqLength)){
  seqData <- c(0:seqLength[k])
  centromereStart <- hg19$centromerStart[hg19$chrom==CHR[k]]
  centromereEnd <- hg19$centromerEnd[hg19$chrom==CHR[k]]
  seqDataList[[k]] <- seqData[-which(seqData %in% c(centromereStart:centromereEnd))]
}
names(seqDataList) <- CHR

```


## ARROWHEAD

### GM12878

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = c("5000","10000","25000","50000","100000")

for(i in 1:length(r)){
  resolution = as.integer(r[i])
  
  domains <- read.table(paste0("Z:/TAD_data_analysis/GSE63525_data/arrowhead_output/GM12878/GM12878_domain_data_",
                               r[i],
                               ".b.txt"))
  
  domains <- domains[which(domains$V1 %in% as.numeric(gsub("CHR","",CHR))),]
  
  numtads[i] <- nrow(domains)
  
  bounds <- extract_boundaries_func(domains.mat=domains, 
                                    preprocess=FALSE, 
                                    CHR=CHR, 
                                    resolution=resolution)
  
  numbounds[i] <- length(bounds)
  
  bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)
  
  data_mat_list <- list()
  outcome_list <- list()
  #full_list <- list()
  #train_list <- list()
  #test_list <- list()
  
  for(j in 1:length(CHR)){
    #start = 0
    start = (resolution/2)
    end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
    #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
    rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
    
    #data_mat_list[[j]] <- matrix(nrow=length(rows),
    #                             ncol=length(genomicElements.GR))
    #rownames(data_mat_list[[j]]) <- rows
    
    outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                               IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                                       start = rows,
                                                       width = resolution)), bounds.GR.flank)
    outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
    outcome_list[[j]] <- factor(outcome_list[[j]])
    levels(outcome_list[[j]]) <- c("No", "Yes")
    
    #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
    #names(full_list[[j]])[1] <- "y"
  }
  ci <- unlist(outcome_list)
  numbins[i] <- length(ci)
  imbalance[i] <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
}

data.frame(resolution = c("5 kb",
                          "10 kb",
                          "25 kb",
                          "50 kb",
                          "100 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

### K562

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = c("5000","10000","25000","50000","100000")

for(i in 1:length(r)){
  resolution = as.integer(r[i])
  
  domains <- read.table(paste0("Z:/TAD_data_analysis/GSE63525_data/arrowhead_output/K562/K562_domain_data_",
                               r[i],
                               ".b.txt"))
  
  domains <- domains[which(domains$V1 %in% as.numeric(gsub("CHR","",CHR))),]
  
  numtads[i] <- nrow(domains)
  
  bounds <- extract_boundaries_func(domains.mat=domains, 
                                    preprocess=FALSE, 
                                    CHR=CHR, 
                                    resolution=resolution)
  
  numbounds[i] <- length(bounds)
  
  bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)
  
  data_mat_list <- list()
  outcome_list <- list()
  #full_list <- list()
  #train_list <- list()
  #test_list <- list()
  
  for(j in 1:length(CHR)){
    print(c(r[i],CHR[j]))
    #start = 0
    start = (resolution/2)
    end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
    #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
    rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
    
    #data_mat_list[[j]] <- matrix(nrow=length(rows),
    #                             ncol=length(genomicElements.GR))
    #rownames(data_mat_list[[j]]) <- rows
    
    outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                               IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                                 start = rows,
                                                 width = resolution)), bounds.GR.flank)
    outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
    outcome_list[[j]] <- factor(outcome_list[[j]])
    levels(outcome_list[[j]]) <- c("No", "Yes")
    
    #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
    #names(full_list[[j]])[1] <- "y"
  }
  ci <- unlist(outcome_list)
  numbins[i] <- length(ci)
  imbalance[i] <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
}

data.frame(resolution = c("5 kb",
                          "10 kb",
                          "25 kb",
                          "50 kb",
                          "100 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

## SpectralTAD

### GM12878

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = c("5","10","25","50","100")

for(i in 1:length(r)){
  resolution = as.integer(r[i])*1000
  
  domains <- as.data.frame(readRDS(paste0("/home/stilianoudakisc/TAD_data_analysis/spectralTAD/GM12878/domain_data_gm12878_",
                                          r[i],
                                          "kb.rds")))
  
  domains <- domains[which(domains$chr %in% as.numeric(gsub("CHR","",CHR))),]
  
  numtads[i] <- nrow(domains)
  
  bounds <- extract_boundaries_func(domains.mat=domains, 
                                    preprocess=FALSE, 
                                    CHR=CHR, 
                                    resolution=resolution)
  
  numbounds[i] <- length(bounds)
  
  bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)
  
  data_mat_list <- list()
  outcome_list <- list()
  #full_list <- list()
  #train_list <- list()
  #test_list <- list()
  
  for(j in 1:length(CHR)){
    print(c(r[i],CHR[j]))
    #start = 0
    start = (resolution/2)
    end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
    #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
    rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
    
    #data_mat_list[[j]] <- matrix(nrow=length(rows),
    #                             ncol=length(genomicElements.GR))
    #rownames(data_mat_list[[j]]) <- rows
    
    outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                               IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                                 start = rows,
                                                 width = resolution)), bounds.GR.flank)
    outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
    outcome_list[[j]] <- factor(outcome_list[[j]])
    levels(outcome_list[[j]]) <- c("No", "Yes")
    
    #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
    #names(full_list[[j]])[1] <- "y"
  }
  ci <- unlist(outcome_list)
  numbins[i] <- length(ci)
  imbalance[i] <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
}

data.frame(resolution = c("5 kb",
                          "10 kb",
                          "25 kb",
                          "50 kb",
                          "100 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

### K562

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = c("5","10","25","50","100")

for(i in 1:length(r)){
  resolution = as.integer(r[i])*1000
  
  domains <- as.data.frame(readRDS(paste0("/home/stilianoudakisc/TAD_data_analysis/spectralTAD/K562/domain_data_k562_",
                                          r[i],
                                          "kb.rds")))
  
  domains <- domains[which(domains$chr %in% as.numeric(gsub("CHR","",CHR))),]
  
  numtads[i] <- nrow(domains)
  
  bounds <- extract_boundaries_func(domains.mat=domains, 
                                    preprocess=FALSE, 
                                    CHR=CHR, 
                                    resolution=resolution)
  
  numbounds[i] <- length(bounds)
  
  bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)
  
  data_mat_list <- list()
  outcome_list <- list()
  #full_list <- list()
  #train_list <- list()
  #test_list <- list()
  
  for(j in 1:length(CHR)){
    print(c(r[i],CHR[j]))
    #start = 0
    start = (resolution/2)
    end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
    #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
    rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
    
    #data_mat_list[[j]] <- matrix(nrow=length(rows),
    #                             ncol=length(genomicElements.GR))
    #rownames(data_mat_list[[j]]) <- rows
    
    outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                               IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                                 start = rows,
                                                 width = resolution)), bounds.GR.flank)
    outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
    outcome_list[[j]] <- factor(outcome_list[[j]])
    levels(outcome_list[[j]]) <- c("No", "Yes")
    
    #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
    #names(full_list[[j]])[1] <- "y"
  }
  ci <- unlist(outcome_list)
  numbins[i] <- length(ci)
  imbalance[i] <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
}

data.frame(resolution = c("5 kb",
                          "10 kb",
                          "25 kb",
                          "50 kb",
                          "100 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

## PEAKACHU

### GM12878

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = "10000"

#for(i in 1:length(r)){
resolution = as.integer(r)

domains <- readRDS("/home/stilianoudakisc/TAD_data_analysis/peakachu/peakachu_GM12878.rds")

domains <- domains[which(domains$chr %in% as.numeric(gsub("CHR","",CHR))),]

numtads <- nrow(domains)

bounds <- extract_boundaries_func(domains.mat=domains, 
                                  preprocess=FALSE, 
                                  CHR=CHR, 
                                  resolution=resolution)

numbounds <- length(bounds)

bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)

data_mat_list <- list()
outcome_list <- list()
#full_list <- list()
#train_list <- list()
#test_list <- list()

for(j in 1:length(CHR)){
  print(c(r,CHR[j]))
  #start = 0
  start = (resolution/2)
  end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
  #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
  rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
  
  #data_mat_list[[j]] <- matrix(nrow=length(rows),
  #                             ncol=length(genomicElements.GR))
  #rownames(data_mat_list[[j]]) <- rows
  
  outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                             IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                               start = rows,
                                               width = resolution)), bounds.GR.flank)
  outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
  outcome_list[[j]] <- factor(outcome_list[[j]])
  levels(outcome_list[[j]]) <- c("No", "Yes")
  
  #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
  #names(full_list[[j]])[1] <- "y"
}
ci <- unlist(outcome_list)
numbins <- length(ci)
imbalance <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
#}

data.frame(resolution = c("10 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

### K562

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = "10000"

#for(i in 1:length(r)){
resolution = as.integer(r)

domains <- readRDS("/home/stilianoudakisc/TAD_data_analysis/peakachu/peakachu_K562.rds")

domains <- domains[which(domains$chr %in% as.numeric(gsub("CHR","",CHR))),]

numtads <- nrow(domains)

bounds <- extract_boundaries_func(domains.mat=domains, 
                                  preprocess=FALSE, 
                                  CHR=CHR, 
                                  resolution=resolution)

numbounds <- length(bounds)

bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)

data_mat_list <- list()
outcome_list <- list()
#full_list <- list()
#train_list <- list()
#test_list <- list()

for(j in 1:length(CHR)){
  print(c(r,CHR[j]))
  #start = 0
  start = (resolution/2)
  end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
  #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
  rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
  
  #data_mat_list[[j]] <- matrix(nrow=length(rows),
  #                             ncol=length(genomicElements.GR))
  #rownames(data_mat_list[[j]]) <- rows
  
  outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                             IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                               start = rows,
                                               width = resolution)), bounds.GR.flank)
  outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
  outcome_list[[j]] <- factor(outcome_list[[j]])
  levels(outcome_list[[j]]) <- c("No", "Yes")
  
  #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
  #names(full_list[[j]])[1] <- "y"
}
ci <- unlist(outcome_list)
numbins <- length(ci)
imbalance <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
#}

data.frame(resolution = c("10 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

## LOLLIPOP

### GM12878

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = "10000"

#for(i in 1:length(r)){
resolution = as.integer(r)

domains <- readRDS("/home/stilianoudakisc/TAD_data_analysis/lollipop/lollipop_GM12878.rds")

domains <- domains[which(domains$chr %in% as.numeric(gsub("CHR","",CHR))),]

numtads <- nrow(domains)

bounds <- extract_boundaries_func(domains.mat=domains, 
                                  preprocess=FALSE, 
                                  CHR=CHR, 
                                  resolution=resolution)

numbounds <- length(bounds)

bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)

data_mat_list <- list()
outcome_list <- list()
#full_list <- list()
#train_list <- list()
#test_list <- list()

for(j in 1:length(CHR)){
  print(c(r,CHR[j]))
  #start = 0
  start = (resolution/2)
  end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
  #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
  rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
  
  #data_mat_list[[j]] <- matrix(nrow=length(rows),
  #                             ncol=length(genomicElements.GR))
  #rownames(data_mat_list[[j]]) <- rows
  
  outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                             IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                               start = rows,
                                               width = resolution)), bounds.GR.flank)
  outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
  outcome_list[[j]] <- factor(outcome_list[[j]])
  levels(outcome_list[[j]]) <- c("No", "Yes")
  
  #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
  #names(full_list[[j]])[1] <- "y"
}
ci <- unlist(outcome_list)
numbins <- length(ci)
imbalance <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
#}

data.frame(resolution = c("10 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

### K562

```{r}
CHR = paste0("CHR", c(1:8,10:22))
numtads <- numeric()
numbounds <- numeric()
numbins <- numeric()
imbalance <- numeric()
r = "10000"

#for(i in 1:length(r)){
resolution = as.integer(r)

domains <- readRDS("/home/stilianoudakisc/TAD_data_analysis/lollipop/lollipop_K562.rds")

domains <- domains[which(domains$chr %in% as.numeric(gsub("CHR","",CHR))),]

numtads <- nrow(domains)

bounds <- extract_boundaries_func(domains.mat=domains, 
                                  preprocess=FALSE, 
                                  CHR=CHR, 
                                  resolution=resolution)

numbounds <- length(bounds)

bounds.GR.flank <- flank(bounds, width=(resolution/2), both=TRUE)

data_mat_list <- list()
outcome_list <- list()
#full_list <- list()
#train_list <- list()
#test_list <- list()

for(j in 1:length(CHR)){
  print(c(r,CHR[j]))
  #start = 0
  start = (resolution/2)
  end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% resolution) + (resolution/2)
  #end = seqDataList[[j]][length(seqDataList[[j]])] - (seqDataList[[j]][length(seqDataList[[j]])] %% (resolution/2))
  rows = seqDataList[[j]][seqDataList[[j]] %in% seq(start, end, resolution)]
  
  #data_mat_list[[j]] <- matrix(nrow=length(rows),
  #                             ncol=length(genomicElements.GR))
  #rownames(data_mat_list[[j]]) <- rows
  
  outcome_list[[j]] <- countOverlaps(GRanges(seqnames = tolower(CHR[j]),
                                             IRanges(#start = as.numeric(rownames(data_mat_list[[j]])),
                                               start = rows,
                                               width = resolution)), bounds.GR.flank)
  outcome_list[[j]] <- ifelse(outcome_list[[j]],1,0)
  outcome_list[[j]] <- factor(outcome_list[[j]])
  levels(outcome_list[[j]]) <- c("No", "Yes")
  
  #full_list[[j]] <- cbind.data.frame(outcome_list[[j]], data_mat_list[[j]])
  #names(full_list[[j]])[1] <- "y"
}
ci <- unlist(outcome_list)
numbins <- length(ci)
imbalance <- as.numeric(round(table(ci)[2]/sum(table(ci)),2))
#}

data.frame(resolution = c("10 kb"),
           numtads=numtads,
           numbounds=numbounds,
           numbins=numbins,
           imbalance=imbalance)

```

