---
title: "Correlations between PTBP at different resolutions"
author: "Spiro Stilianoudakis"
date: "5/28/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages and functions

```{r}
library(S4Vectors)
library(GenomicRanges)
library(ggplot2)
library(caret)
library(randomForest)
library(glmnet)
library(gbm)
library(DMwR)
library(rtracklayer)
library(Biostrings)
library(BSgenome)
library(cluster)
library(pROC)
library(SuperLearner)
library(data.table)
library(PRROC)
library(bigmemory)
library(ranger)
library(dplyr)
library(parallel)
library(doSNOW)
library(foreach)
library(pbapply)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)
library(GenometriCorr)
library(ggsignif)
library(Vennerable)
library(VennDiagram)
library(ChIPpeakAnno)
library(EnrichedHeatmap)
library(ComplexHeatmap)
library(circlize)
library(cotools)
library(ggcorrplot)
library(circlize)

source("Z:/TAD_data_analysis/functions_for_R_package/preciseTAD.R")
source("Z:/TAD_data_analysis/functions_for_R_package/TADRF.R")
source("Z:/TAD_data_analysis/functions_for_R_package/TADrfe.R")
source("Z:/TAD_data_analysis/functions_for_R_package/distance_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/percent_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/count_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/binary_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/signal_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/annots_to_granges_func.R")
source("Z:/TAD_data_analysis/functions_for_R_package/extract_boundaries_func.R")

```

# Jaccard Function

```{r}
jaccard_mod <- function (query, reference, restrict = NULL, modified=FALSE) {
  if(isTRUE(modified)){
    int = sum(width(GenomicRanges::intersect(query, reference)))
    minunion = min(sum(as.numeric(width(GenomicRanges::intersect(query, reference)))),sum(as.numeric(width(GenomicRanges::union(query, reference)))))
    res = int/minunion
  }else{
    res = sum(width(GenomicRanges::intersect(query, reference)))/sum(as.numeric(width(GenomicRanges::union(query, reference)))) 
  }
  return(res)
}

genomicCorr.jaccard = function(query, reference, restrict = NULL) {
	if(is.null(restrict)) {
		res = sum(width(GenomicRanges::intersect(query, reference))) / sum(as.numeric(width(GenomicRanges::union(query, reference))))
	} else {
		gr1 = GenomicRanges::intersect(query, reference)
		gr1 = GenomicRanges::intersect(gr1, restrict)

		gr2 = GenomicRanges::union(query, reference)
		gr2 = GenomicRanges::intersect(gr2, restrict)
		res = sum(width(gr1)) / sum(width(gr2))
	}
	return(res)
}
```


## GM12878

```{r}
gm12878_5kb <- readRDS("Z:/TAD_data_analysis/GM12878/5kb/results_by_chr/CHR1/rus/distance/preciseTAD_holdout.rds")
gm12878_10kb <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/CHR1/rus/distance/preciseTAD_holdout.rds")
gm12878_25kb <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/results_by_chr/CHR1/rus/distance/preciseTAD_holdout.rds")
gm12878_50kb <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/results_by_chr/CHR1/rus/distance/preciseTAD_holdout.rds")
gm12878_100kb <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/results_by_chr/CHR1/rus/distance/preciseTAD_holdout.rds")

pt_gm12878_5kb <- flank(gm12878_5kb[[2]], 5000, both=TRUE)
pt_gm12878_10kb <- flank(gm12878_10kb[[2]], 10000, both=TRUE)
pt_gm12878_25kb <- flank(gm12878_25kb[[2]], 25000, both=TRUE)
pt_gm12878_50kb <- flank(gm12878_50kb[[2]], 50000, both=TRUE)
pt_gm12878_100kb <- flank(gm12878_100kb[[2]], 100000, both=TRUE)

arrow_gm12878_5kb <- flank(gm12878_5kb[[3]], 5000, both=TRUE)
arrow_gm12878_10kb <- flank(gm12878_10kb[[3]], 10000, both=TRUE)
arrow_gm12878_25kb <- flank(gm12878_25kb[[3]], 25000, both=TRUE)
arrow_gm12878_50kb <- flank(gm12878_50kb[[3]], 50000, both=TRUE)
arrow_gm12878_100kb <- flank(gm12878_100kb[[3]], 100000, both=TRUE)

jaccard_matrix <- matrix(nrow=5,ncol=5)
jaccard_matrix[1,2] <- round(genomicCorr.jaccard(pt_gm12878_5kb,pt_gm12878_10kb),2)
jaccard_matrix[1,3] <- round(genomicCorr.jaccard(pt_gm12878_5kb,pt_gm12878_25kb),2)
jaccard_matrix[1,4] <- round(genomicCorr.jaccard(pt_gm12878_5kb,pt_gm12878_50kb),2)
jaccard_matrix[1,5] <- round(genomicCorr.jaccard(pt_gm12878_5kb,pt_gm12878_100kb),2)
jaccard_matrix[2,3] <- round(genomicCorr.jaccard(pt_gm12878_10kb,pt_gm12878_25kb),2)
jaccard_matrix[2,4] <- round(genomicCorr.jaccard(pt_gm12878_10kb,pt_gm12878_50kb),2)
jaccard_matrix[2,5] <- round(genomicCorr.jaccard(pt_gm12878_10kb,pt_gm12878_100kb),2)
jaccard_matrix[3,4] <- round(genomicCorr.jaccard(pt_gm12878_25kb,pt_gm12878_50kb),2)
jaccard_matrix[3,5] <- round(genomicCorr.jaccard(pt_gm12878_25kb,pt_gm12878_100kb),2)
jaccard_matrix[4,5] <- round(genomicCorr.jaccard(pt_gm12878_50kb,pt_gm12878_100kb),2)

jaccard_matrix[2,1] <- round(genomicCorr.jaccard(arrow_gm12878_5kb,arrow_gm12878_10kb),2)
jaccard_matrix[3,1] <- round(genomicCorr.jaccard(arrow_gm12878_5kb,arrow_gm12878_25kb),2)
jaccard_matrix[4,1] <- round(genomicCorr.jaccard(arrow_gm12878_5kb,arrow_gm12878_50kb),2)
jaccard_matrix[5,1] <- round(genomicCorr.jaccard(arrow_gm12878_5kb,arrow_gm12878_100kb),2)
jaccard_matrix[3,2] <- round(genomicCorr.jaccard(arrow_gm12878_10kb,arrow_gm12878_25kb),2)
jaccard_matrix[4,2] <- round(genomicCorr.jaccard(arrow_gm12878_10kb,arrow_gm12878_50kb),2)
jaccard_matrix[5,2] <- round(genomicCorr.jaccard(arrow_gm12878_10kb,arrow_gm12878_100kb),2)
jaccard_matrix[4,3] <- round(genomicCorr.jaccard(arrow_gm12878_25kb,arrow_gm12878_50kb),2)
jaccard_matrix[5,3] <- round(genomicCorr.jaccard(arrow_gm12878_25kb,arrow_gm12878_100kb),2)
jaccard_matrix[5,4] <- round(genomicCorr.jaccard(arrow_gm12878_50kb,arrow_gm12878_100kb),2)

rownames(jaccard_matrix) <- colnames(jaccard_matrix) <- c("5 kb", "10 kb", "25 kb", "50 kb", "100 kb")

col_fun = colorRamp2(c(0,.3,.6), c("blue","white","red"))
col_fun = colorRamp2(c(0,.6), c("white","red"))
Heatmap(jaccard_matrix,  
        col = col_fun,
        cell_fun = function(j, i, x, y, width, height, fill) {
            if(i==j){
              grid.text(sprintf("%.2f", jaccard_matrix[i, j]), x, y, gp = gpar(fontsize = 0))
            }else{grid.text(sprintf("%.2f", jaccard_matrix[i, j]), x, y, gp = gpar(fontsize = 15))}
          },
        cluster_rows = FALSE,
        cluster_columns = FALSE, 
        na_col = "gray",
        show_heatmap_legend = FALSE,
        rect_gp = gpar(col = "black", lwd = 1),
        show_row_names = TRUE,
        row_names_side = c("left"),
        row_names_gp = gpar(fontsize = 15),
        show_column_names = TRUE,
        column_names_side = c("bottom"),
        column_names_gp = gpar(fontsize = 15),
        column_names_rot = 45,
        column_names_centered = FALSE)

col <- colorRampPalette(c("blue","white","red"))
corrplot(jaccard_matrix, 
         method="color", 
         col=col(100),  
         type="full", 
         order="original", 
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", 
         tl.srt=45, #Text label color and rotation
         # Combine with significance
         #p.mat = p.mat, 
         #sig.level = 0.01, 
         #insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
```


## K562

