---
title: "Comparing distance distributions for top predictive features between bins with and without TADs"
author: "Spiro Stilianoudakis"
date: "April 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)
library(coin)
```


# GM12878

## 10kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "Gm12878", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Smc3ab9263-Sydh_dist"))
  
p.gm12878.10kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Znf143166181ap-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Znf143166181ap-Sydh_dist"))
  
p.gm12878.10kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143166181ap_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Ctcf-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Ctcf-Broad_dist"))
  
p.gm12878.10kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcf_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Rad21-Haib_dist"))
  
p.gm12878.10kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```

## 25kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/25kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/25kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "Gm12878", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Smc3ab9263-Sydh_dist"))
  
p.gm12878.25kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Znf143166181ap-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Znf143166181ap-Sydh_dist"))
  
p.gm12878.25kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143166181ap_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Ctcf-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Ctcf-Broad_dist"))
  
p.gm12878.25kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcf_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Rad21-Haib_dist"))
  
p.gm12878.25kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


## 50kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/50kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/50kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "Gm12878", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Smc3ab9263-Sydh_dist"))
  
p.gm12878.50kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Znf143166181ap-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Znf143166181ap-Sydh_dist"))
  
p.gm12878.50kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143166181ap_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Ctcf-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Ctcf-Broad_dist"))
  
p.gm12878.50kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcf_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Rad21-Haib_dist"))
  
p.gm12878.50kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


## 100kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/100kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/100kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "Gm12878", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Smc3ab9263-Sydh_dist"))
  
p.gm12878.100kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Znf143166181ap-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Znf143166181ap-Sydh_dist"))
  
p.gm12878.100kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143166181ap_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Ctcf-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Ctcf-Broad_dist"))
  
p.gm12878.100kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcf_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "Gm12878", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "Gm12878-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("Gm12878",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "Gm12878-Rad21-Haib_dist"))
  
p.gm12878.100kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


# K562

## 10kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/K562/10kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/K562/10kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "K562", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Smc3ab9263-Sydh_dist"))
  
p.K562.10kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Znf143-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Znf143-Sydh_dist"))
  
p.K562.10kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Ctcfc-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Ctcfc-Broad_dist"))
  
p.K562.10kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcfc_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Rad21-Haib_dist"))
  
p.K562.10kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```

## 25kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/K562/25kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/K562/25kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "K562", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Smc3ab9263-Sydh_dist"))
  
p.K562.25kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Znf143-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Znf143-Sydh_dist"))
  
p.K562.25kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Ctcfc-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Ctcfc-Broad_dist"))
  
p.K562.25kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcfc_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Rad21-Haib_dist"))
  
p.K562.25kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


## 50kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/K562/50kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/K562/50kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "K562", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Smc3ab9263-Sydh_dist"))
  
p.K562.50kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Znf143-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Znf143-Sydh_dist"))
  
p.K562.50kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Ctcfc-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Ctcfc-Broad_dist"))
  
p.K562.50kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcfc_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Rad21-Haib_dist"))
  
p.K562.50kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


## 100kb

```{r}
train <- readRDS(paste0("Z:/TAD_data_analysis/K562/100kb/training_testing/train.rds"))
  
enetcoefs <- readRDS(paste0("Z:/TAD_data_analysis/K562/100kb/Ensemble/SMOTE/Distance/ENET/enetcoefs.rds"))
 
names(train) <- gsub(paste(c("`", 
                             "K562", 
                             "-", 
                             #"_", 
                             #"dist", "count", "perc",
                             "Haib", 
                             "Sydh",
                             "Uta",
                             "Uw",
                             "Broad",
                             "Uchicago"), collapse = "|"), "", names(train))
train <- train[,c(1,which(names(train) %in% enetcoefs))]

  
set.seed(123)
train_smote <- SMOTE(y ~ ., 
                     data=train, 
                     perc.over = 100, 
                     perc.under = 200)
  
  
```


### Top Annotations

####SMC

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Smc3ab9263-Sydh_dist")
  
annotdata.smc <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.smc[which(annotdata.smc$y=="No"),2], annotdata.smc[which(annotdata.smc$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.smc[,2] ~ annotdata.smc[,1],
                     data=annotdata.smc,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Smc3ab9263-Sydh_dist"))
  
p.K562.100kb.smc <- ggplot(annotdata.smc, aes(x=Smc3ab9263_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("SMC3a\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####ZNF143

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Znf143-Sydh_dist")
  
annotdata.znf143 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.znf143[which(annotdata.znf143$y=="No"),2], annotdata.znf143[which(annotdata.znf143$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.znf143[,2] ~ annotdata.znf143[,1],
                     data=annotdata.znf143,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Znf143-Sydh_dist"))
  
p.K562.100kb.znf143 <- ggplot(annotdata.znf143, aes(x=Znf143_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("ZNF143\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####CTCF

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Ctcfc-Broad_dist")
  
annotdata.ctcf <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.ctcf[which(annotdata.ctcf$y=="No"),2], annotdata.ctcf[which(annotdata.ctcf$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.ctcf[,2] ~ annotdata.ctcf[,1],
                     data=annotdata.ctcf,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Ctcfc-Broad_dist"))
  
p.K562.100kb.ctcf <- ggplot(annotdata.ctcf, aes(x=Ctcfc_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("CTCF\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```


####RAD21

```{r}
annotname <- gsub(paste(c("`", 
             "K562", 
             "-", 
             #"_", 
             #"dist", "count", "perc",
             "Haib", 
             "Sydh",
             "Uta",
             "Uw",
             "Broad",
             "Uchicago"), collapse = "|"), "", "K562-Rad21-Haib_dist")
  
annotdata.rad21 <- train_smote[, c(1, which(names(train_smote)==annotname))]
  
#ks.test(annotdata.rad21[which(annotdata.rad21$y=="No"),2], annotdata.rad21[which(annotdata.rad21$y=="Yes"),2], alternative = "two.sided")
  
perm.pval <- pvalue(oneway_test(annotdata.rad21[,2] ~ annotdata.rad21[,1],
                     data=annotdata.rad21,
                     alternative="greater", 
                     distribution=approximate(B=10000)))[1]
  
perm.pval <- ifelse(perm.pval==0,"< 0.0001", as.character(round(perm.pval,4)))
  
plottitle <- paste(gsub(paste(c("K562",
                                  "-","_",
                                  "dist","perc","count",
                                  "Haib",
                                  "Sydh",
                                  "Uta",
                                  "Uw",
                                  "Broad",
                                  "Uchicago"), 
                                collapse = "|"), 
                          "",
                          "K562-Rad21-Haib_dist"))
  
p.K562.100kb.rad21 <- ggplot(annotdata.rad21, aes(x=Rad21_dist, color=y)) +
    geom_density() +
    scale_color_discrete(name="Class of\nGenomic Bin",
                         labels=c("Does not overlap\nw/ flanked TAD boundary", "Overlapped w/\nflanked TAD boundary")) +
    ylab("") +
    xlab("") +
    ggtitle("RAD21\nPermutation P-Value: < 0.0001") +
    #annotate("text", x=7, y=.2, label= paste("P-Value:", perm.pval, sep = " "), size=5) +
    theme_bw() +
    theme(axis.text.x = element_text(size=15 #,
                                     #angle = 45, 
                                     #margin = ggplot2::margin(t = 35),
                                     #hjust = 1
    ),
    axis.text.y = element_text(size = 15),
    axis.title.x = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.text=element_text(size=15),
    legend.title=element_text(size=20),
    plot.title = element_text(size=20,
                              hjust=.5))
```
