---
title: "Comparing distance distributions for top predictive features between bins with and without TADs"
author: "Spiro Stilianoudakis"
date: "April 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)
library(coin)
library(ggsignif)
```


# GM12878

## Top annotations

```{r}
annots <- c("Gm12878-Smc3ab9263-Sydh_dist",
            "Gm12878-Ctcf-Broad_dist",
            "Gm12878-Znf143166181ap-Sydh_dist",
            "Gm12878-Yy1sc281-Haib_dist",
            "Gm12878-Rad21-Haib_dist")
```

### 10kb

```{r}

dist_list_gm12878_10kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/training_testing/gm12878_10kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/training_testing/binslist10.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "10 kb"
		
	  dist_list_gm12878_10kb[[i]] <- train
    
}

dist_gm12878_10kb <- do.call("rbind", dist_list_gm12878_10kb)

#dist_gm12878_10kb_summ <- dist_gm12878_10kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`Gm12878-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`Gm12878-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`Gm12878-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`Gm12878-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`Gm12878-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```

### 25kb

```{r}

dist_list_gm12878_25kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/training_testing/gm12878_25kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/training_testing/binslist25.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "25 kb"
		
	  dist_list_gm12878_25kb[[i]] <- train
    
}

dist_gm12878_25kb <- do.call("rbind", dist_list_gm12878_25kb)

#dist_gm12878_25kb_summ <- dist_gm12878_25kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`Gm12878-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`Gm12878-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`Gm12878-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`Gm12878-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`Gm12878-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```

### 50kb

```{r}

dist_list_gm12878_50kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/training_testing/gm12878_50kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/training_testing/binslist50.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "50 kb"
		
	  dist_list_gm12878_50kb[[i]] <- train
    
}

dist_gm12878_50kb <- do.call("rbind", dist_list_gm12878_50kb)

#dist_gm12878_50kb_summ <- dist_gm12878_50kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`Gm12878-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`Gm12878-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`Gm12878-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`Gm12878-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`Gm12878-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```

### 100kb

```{r}

dist_list_gm12878_100kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/training_testing/gm12878_100kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/training_testing/binslist100.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "100 kb"
		
	  dist_list_gm12878_100kb[[i]] <- train
    
}

dist_gm12878_100kb <- do.call("rbind", dist_list_gm12878_100kb)

#dist_gm12878_100kb_summ <- dist_gm12878_100kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`Gm12878-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`Gm12878-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`Gm12878-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`Gm12878-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`Gm12878-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```

## Plots

```{r}
all_dist_gm12878 <- rbind.data.frame(dist_gm12878_10kb,
                                     dist_gm12878_25kb,
                                     dist_gm12878_50kb,
                                     dist_gm12878_100kb)

names(all_dist_gm12878) <- c("y", "CTCF", "RAD21", "SMC3", "YY1sc281", "ZNF143", "CHR", "Resolution")

all_dist_gm12878$Resolution <- factor(all_dist_gm12878$Resolution, levels=c("10 kb", "25 kb", "50 kb", "100 kb"))

all_dist_gm12878 <- melt(all_dist_gm12878)

all_dist_gm12878$variable <- factor(all_dist_gm12878$variable, levels=c("SMC3", "CTCF", "RAD21", "ZNF143", "YY1sc281"))


# 10 kb
all_dist_gm12878_10kb <- ggplot(all_dist_gm12878[which(all_dist_gm12878$Resolution=="10 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("Transcription Factor\nBinding Site") +
  ylab("Log2 Distance") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))

# 25 kb
all_dist_gm12878_25kb <- ggplot(all_dist_gm12878[which(all_dist_gm12878$Resolution=="25 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("") +
  ylab("") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))
		
		
# 50 kb
all_dist_gm12878_50kb <- ggplot(all_dist_gm12878[which(all_dist_gm12878$Resolution=="50 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("") +
  ylab("") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))
		

# 100 kb
all_dist_gm12878_100kb <- ggplot(all_dist_gm12878[which(all_dist_gm12878$Resolution=="100 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("") +
  ylab("") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))

figure <- ggarrange(all_dist_gm12878_25kb,
                    all_dist_gm12878_50kb,
                    all_dist_gm12878_100kb,
                    ncol = 1,
                    nrow = 3,
                    common.legend = TRUE,
                    legend = "top",
                    labels = "AUTO",
                    font.label = list(size=20))
figure 
annotate_figure(figure, 
                bottom = text_grob("Transcription Factor\nBinding Site", color = "black", size = 20),
                left = text_grob("Log2 Distance", color = "black", size = 20, rot=90))
```


# K562

## Top annotations

```{r}
annots <- c("K562-Smc3ab9263-Sydh_dist",
            "K562-Ctcf-Broad_dist",
            "K562-Znf143-Sydh_dist",
            #"K562-Yy1sc281-Haib_dist",
            "K562-Rad21-Haib_dist")
```

### 10kb

```{r}

dist_list_K562_10kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/K562/10kb/training_testing/K562_10kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/K562/10kb/training_testing/binslist10.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "10 kb"
		
	  dist_list_K562_10kb[[i]] <- train
    
}

dist_K562_10kb <- do.call("rbind", dist_list_K562_10kb)

#dist_K562_10kb_summ <- dist_K562_10kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`K562-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`K562-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`K562-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`K562-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`K562-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```

### 25kb

```{r}

dist_list_K562_25kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/K562/25kb/training_testing/K562_25kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/K562/25kb/training_testing/binslist25.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "25 kb"
		
	  dist_list_K562_25kb[[i]] <- train
    
}

dist_K562_25kb <- do.call("rbind", dist_list_K562_25kb)

#dist_K562_25kb_summ <- dist_K562_25kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`K562-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`K562-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`K562-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`K562-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`K562-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```

### 50kb

```{r}

dist_list_K562_50kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/K562/50kb/training_testing/K562_50kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/K562/50kb/training_testing/binslist50.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "50 kb"
		
	  dist_list_K562_50kb[[i]] <- train
    
}

dist_K562_50kb <- do.call("rbind", dist_list_K562_50kb)

#dist_K562_50kb_summ <- dist_K562_50kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`K562-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`K562-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`K562-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`K562-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`K562-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```

### 100kb

```{r}

dist_list_K562_100kb <- list()

chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
	  whole_genome_dat <- readRDS("Z:/TAD_data_analysis/K562/100kb/training_testing/K562_100kb.rds")
	  
	  binslist_dat <- readRDS("Z:/TAD_data_analysis/K562/100kb/training_testing/binslist100.rds")
	  
	  reduce_chr <- tolower(chrs[i])
	  chr_specific_dat <- whole_genome_dat[which(as.character(seqnames(binslist_dat))==reduce_chr),
	                                       c(1, which(names(whole_genome_dat) %in% annots))]
	  
	  set.seed(123)
	  inTrainingSet <- sample(length(chr_specific_dat$y),floor(length(chr_specific_dat$y)*.7))
    train <- chr_specific_dat[inTrainingSet,]
    
    set.seed(123)
	  train <- SMOTE(y ~ ., 
	                 data=train, 
                   perc.over = 100, 
                   perc.under = 200)
	  train$CHR <- chrs[i]
	  train$Resolution <- "100 kb"
		
	  dist_list_K562_100kb[[i]] <- train
    
}

dist_K562_100kb <- do.call("rbind", dist_list_K562_100kb)

#dist_K562_100kb_summ <- dist_K562_100kb %>%
#  dplyr::group_by(y,CHR) %>%
#  dplyr::summarise(Ctcf = mean(`K562-Ctcf-Broad_dist`, na.rm = TRUE),
#                   Rad21 = mean(`K562-Rad21-Haib_dist`, na.rm = TRUE),
#                   Smc3ab9263 = mean(`K562-Smc3ab9263-Sydh_dist`, na.rm = TRUE),
#                   Yy1sc281 = mean(`K562-Yy1sc281-Haib_dist`, na.rm = TRUE),
#                   Znf143166181ap = mean(`K562-Znf143166181ap-Sydh_dist`, na.rm = TRUE))


```


## Plots

```{r}
all_dist_K562 <- rbind.data.frame(dist_K562_10kb,
                                     dist_K562_25kb,
                                     dist_K562_50kb,
                                     dist_K562_100kb)

names(all_dist_K562) <- c("y", "CTCF", "RAD21", "SMC3", "ZNF143", "CHR", "Resolution")

all_dist_K562$Resolution <- factor(all_dist_K562$Resolution, levels=c("10 kb", "25 kb", "50 kb", "100 kb"))

all_dist_K562 <- melt(all_dist_K562)

all_dist_K562$variable <- factor(all_dist_K562$variable, levels=c("SMC3", "CTCF", "RAD21", "ZNF143"))


# 10 kb
all_dist_K562_10kb <- ggplot(all_dist_K562[which(all_dist_K562$Resolution=="10 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("") +
  ylab("") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))

# 25 kb
all_dist_K562_25kb <- ggplot(all_dist_K562[which(all_dist_K562$Resolution=="25 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("") +
  ylab("") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))
		
		
# 50 kb
all_dist_K562_50kb <- ggplot(all_dist_K562[which(all_dist_K562$Resolution=="50 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("") +
  ylab("") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))
		

# 100 kb
all_dist_K562_100kb <- ggplot(all_dist_K562[which(all_dist_K562$Resolution=="100 kb"),], aes(x = y, y = value, fill = y)) +
  facet_grid(~ variable) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot() +
  stat_compare_means(comparisons = list(c("No", "Yes")), 
                     method = "wilcox.test", 
                     label = "p.signif") +
  #facet_grid(~ variable) +
  xlab("") +
  ylab("") +
  #ylim(5,25) +
  scale_fill_discrete(name="Genomic bin overlapped\nw/ flanked TAD boundary") +
  #guides(color=FALSE) +
  theme_minimal() +
  theme_bw() +
  theme(axis.text.x = element_text(size=15#,
                                   #angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   #hjust = 1
                                   ),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))

figure <- ggarrange(all_dist_K562_10kb,
                    all_dist_K562_25kb,
                    all_dist_K562_50kb,
                    all_dist_K562_100kb,
                    ncol = 2,
                    nrow = 2,
                    common.legend = TRUE,
                    legend = "top",
                    labels = "AUTO",
                    font.label = list(size=20))
figure 
annotate_figure(figure, 
                bottom = text_grob("Transcription Factor\nBinding Site", color = "black", size = 20),
                left = text_grob("Log2 Distance", color = "black", size = 20, rot=90))
```