---
title: "Comparing Predicted Boundaries vs Called Boundaries"
author: "Spiro Stilianoudakis"
date: "July 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(scales)
library(GGally)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)
library(GenometriCorr)
library(ggpubr)
library(ggsignif)
library(Vennerable)
library(VennDiagram)
library(ChIPpeakAnno)
```

# Testing what cutoff to use to determine predicted boundary regions

# Create granges from top tfbs

```{r}
source("C:/Users/stili/Documents/TAD_predictive_modeling/Scripts/functions_for_R_package/annots_to_granges_func.r")
#file_path="Z:/TAD_data_analysis/annotations/all_common_annotations/gm12878/chr22_tfbs_gm12878"
file_path="Z:/TAD_data_analysis/annotations/all_common_annotations/gm12878/topTFBS"
annots.GR <- annots_to_granges_func(filepath=file_path)

```

## GM12878; chr22

### 10 pb cutoff

```{r}
toptfbs_10_gm12878_chr22 <- readRDS("Z:/TAD_data_analysis/GM12878/experiments/toptfbs_10.rds")

venn_cnt2venn <- function(venn_cnt){
  n <- which(colnames(venn_cnt)=="Counts") - 1
  SetNames=colnames(venn_cnt)[1:n]
  Weight=venn_cnt[,"Counts"]
  names(Weight) <- apply(venn_cnt[,1:n], 1, paste, collapse="")
  Venn(SetNames=SetNames, Weight=Weight)
}

res <- makeVennDiagram(Peaks=list(toptfbs_10_gm12878_chr22[[3]], toptfbs_10_gm12878_chr22[[4]]),
                       NameOfPeaks=c("Called", "Predicted"),
                       connectedPeaks = "keepAll")
venn_gm12878_22 <- venn_cnt2venn(res$vennCounts)
venn_gm12878_22 <- compute.Venn(venn_gm12878_22)
gp <- VennThemes(venn_gm12878_22)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_gm12878_22, 
                                                 gp = gp, 
                                                 show=list(Universe=FALSE))), 
                        top=textGrob("Boundary Region", 
                                     gp=gpar(fontsize=50)))


############################################################################################################

#PBNC

sh <- unique(subjectHits(findOverlaps(toptfbs_10_gm12878_chr22[[3]], toptfbs_10_gm12878_chr22[[4]])))
pbnc <- toptfbs_10_gm12878_chr22[[4]][-sh]

pbnc_to_ctcf <- GenometriCorrelation(pbnc,
                                     annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                     chromosomes.length = max(end(pbnc),
                                                              end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pbnc_to_rad21 <- GenometriCorrelation(pbnc,
                                      annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                      chromosomes.length = max(end(pbnc),
                                                               end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

pbnc_to_smc3a <- GenometriCorrelation(pbnc,
                                      annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                      chromosomes.length = max(end(pbnc),
                                                               end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

pbnc_to_znf143 <- GenometriCorrelation(pbnc,
                                       annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                       chromosomes.length = max(end(pbnc),
                                                                end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                       chromosomes.to.proceed = "chr22", 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)

############################################################################################################

#PAC
sh <- unique(subjectHits(findOverlaps(toptfbs_10_gm12878_chr22[[3]], toptfbs_10_gm12878_chr22[[4]])))
pac <- toptfbs_10_gm12878_chr22[[4]][sh]

pac_to_ctcf <- GenometriCorrelation(pac,
                                    annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                    chromosomes.length = max(end(pac),
                                                             end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                    chromosomes.to.proceed = "chr22", 
                                    permut.number = 100,
                                    ecdf.area.permut.number = 100,
                                    mean.distance.permut.number = 100,
                                    jaccard.measure.permut.number = 100,
                                    keep.distributions = TRUE, 
                                    showProgressBar = TRUE)

pac_to_rad21 <- GenometriCorrelation(pac,
                                     annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                     chromosomes.length = max(end(pac),
                                                              end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pac_to_smc3a <- GenometriCorrelation(pac,
                                     annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                     chromosomes.length = max(end(pac),
                                                              end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pac_to_znf143 <- GenometriCorrelation(pac,
                                      annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                      chromosomes.length = max(end(pac),
                                                               end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

############################################################################################################

#CAP
qh <- unique(queryHits(findOverlaps(toptfbs_10_gm12878_chr22[[3]], toptfbs_10_gm12878_chr22[[4]])))
cap <- toptfbs_10_gm12878_chr22[[3]][qh]

cap_to_ctcf <- GenometriCorrelation(cap,
                                    annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                    chromosomes.length = max(end(cap),
                                                             end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                    chromosomes.to.proceed = "chr22", 
                                    permut.number = 100,
                                    ecdf.area.permut.number = 100,
                                    mean.distance.permut.number = 100,
                                    jaccard.measure.permut.number = 100,
                                    keep.distributions = TRUE, 
                                    showProgressBar = TRUE)

cap_to_rad21 <- GenometriCorrelation(cap,
                                     annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                     chromosomes.length = max(end(cap),
                                                              end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cap_to_smc3a <- GenometriCorrelation(cap,
                                     annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                     chromosomes.length = max(end(cap),
                                                              end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cap_to_znf143 <- GenometriCorrelation(cap,
                                      annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                      chromosomes.length = max(end(cap),
                                                               end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

###########################################################################################################

#CBNP
qh <- unique(queryHits(findOverlaps(toptfbs_10_gm12878_chr22[[3]], toptfbs_10_gm12878_chr22[[4]])))
cbnp <- toptfbs_10_gm12878_chr22[[3]][-qh]

cbnp_to_ctcf <- GenometriCorrelation(cbnp,
                                     annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                     chromosomes.length = max(end(cbnp),
                                                              end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cbnp_to_rad21 <- GenometriCorrelation(cbnp,
                                      annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                      chromosomes.length = max(end(cbnp),
                                                               end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

cbnp_to_smc3a <- GenometriCorrelation(cbnp,
                                      annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                      chromosomes.length = max(end(cbnp),
                                                               end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

cbnp_to_znf143 <- GenometriCorrelation(cbnp,
                                       annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                       chromosomes.length = max(end(cbnp),
                                                                end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                       chromosomes.to.proceed = "chr22", 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)


############################################################################################################


pred_v_called_10_df <- data.frame(AbsoluteDist = c(#PBNC
  pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data,
  pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data,
  
  #PAC
  pac_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  pac_to_rad21@.Data[[1]]$absolute.min.distance.data,
  pac_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  pac_to_znf143@.Data[[1]]$absolute.min.distance.data,
  
  #CAP
  cap_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  cap_to_rad21@.Data[[1]]$absolute.min.distance.data,
  cap_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  cap_to_znf143@.Data[[1]]$absolute.min.distance.data,
  
  #CBNP
  cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data,
  cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data),
  Annotation = c(#PBNC
    rep("CTCF",length(pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #PAC
    rep("CTCF",length(pac_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(pac_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(pac_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(pac_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CAP
    rep("CTCF",length(cap_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(cap_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(cap_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(cap_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CBNP
    rep("CTCF",length(cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data))),
  BoundReg = c(#PBNC
    rep("PBNC", length(pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("PBNC", length(pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("PBNC", length(pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("PBNC", length(pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #PAC
    rep("PAC", length(pac_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("PAC", length(pac_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("PAC", length(pac_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("PAC", length(pac_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CAP
    rep("CAP", length(cap_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("CAP", length(cap_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("CAP", length(cap_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("CAP", length(cap_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CBNP
    rep("CBNP", length(cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("CBNP", length(cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("CBNP", length(cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("CBNP", length(cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data))))
pred_v_called_10_df$BoundReg <- factor(pred_v_called_10_df$BoundReg, levels=c("PBNC", "PAC", "CAP", "CBNP"))
pred_v_called_10_df$log2AbsoluteDist <- log(pred_v_called_10_df$AbsoluteDist + 1, base = 2)

ggplot(pred_v_called_10_df, aes(x=BoundReg, y = log2AbsoluteDist, fill=BoundReg))  + 
  facet_grid(~ Annotation) +    
  stat_boxplot(geom ='errorbar', width = 0.2) + 
  geom_boxplot(outlier.shape = NA) +
  #stat_compare_means(comparisons = list( c("PBNC", "PAC"), 
  #                                       c("PBNC", "CAP"), 
  #                                       c("PBNC", "CBNP"),
  #                                       c("PAC", "CAP"),
  #                                       c("PAC", "CBNP"),
  #                                       c("CAP", "CBNP")),
  #                   vjust = 0,
  #                   #textsize = 4,
  #                   #size = .5,
  #                   #step_increase = .08, 
  #                   method = "wilcox.test", 
  #                   label = "p.format") +
  geom_signif(test = "wilcox.test", 
              comparisons = list( c("PBNC", "PAC"), 
                                  c("PBNC", "CAP"), 
                                  c("PBNC", "CBNP"),
                                  c("PAC", "CAP"),
                                  c("PAC", "CBNP"),
                                  c("CAP", "CBNP")),
              vjust = 0,
              textsize = 4,
              size = .5,
              step_increase = .08) +
  theme_minimal()+
  theme_bw()+
  ylab("Log2 Distance to Annotation")+
  xlab("") +
  ggtitle("10 bp width cutoff")+
  scale_fill_discrete(name="Boundary Region")+
  scale_x_discrete(labels=c("PBNC"="Predicted but\nnot called",
                           "PAC"="Predicted\nand called",
                           "CAP"="Called and\npredicted",
                           "CBNP"="Called but not\npredicted"))+
  #guides(color=FALSE, linetype=FALSE)+
  theme(axis.text.x = element_text(size=15,
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        strip.text.x = element_text(size = 15),
        #panel.spacing = unit(2, "lines"),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        plot.title = element_text(size=20),
        legend.position = "bottom")

```

### Median length of adjacent 1bp cutoff

```{r}
toptfbs_median_gm12878_chr22 <- readRDS("Z:/TAD_data_analysis/GM12878/experiments/toptfbs_median.rds")

venn_cnt2venn <- function(venn_cnt){
  n <- which(colnames(venn_cnt)=="Counts") - 1
  SetNames=colnames(venn_cnt)[1:n]
  Weight=venn_cnt[,"Counts"]
  names(Weight) <- apply(venn_cnt[,1:n], 1, paste, collapse="")
  Venn(SetNames=SetNames, Weight=Weight)
}

res <- makeVennDiagram(Peaks=list(toptfbs_median_gm12878_chr22[[3]], toptfbs_median_gm12878_chr22[[4]]),
                       NameOfPeaks=c("Called", "Predicted"),
                       connectedPeaks = "keepAll")
venn_gm12878_22 <- venn_cnt2venn(res$vennCounts)
venn_gm12878_22 <- compute.Venn(venn_gm12878_22)
gp <- VennThemes(venn_gm12878_22)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_5kb, 
                                                 gp = gp, 
                                                 show=list(Universe=FALSE))), 
                        top=textGrob("Boundary Region", 
                                     gp=gpar(fontsize=50)))


############################################################################################################

#PBNC

sh <- unique(subjectHits(findOverlaps(toptfbs_median_gm12878_chr22[[3]], toptfbs_median_gm12878_chr22[[4]])))
pbnc <- toptfbs_median_gm12878_chr22[[4]][-sh]

pbnc_to_ctcf <- GenometriCorrelation(pbnc,
                                     annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                     chromosomes.length = max(end(pbnc),
                                                              end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pbnc_to_rad21 <- GenometriCorrelation(pbnc,
                                      annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                      chromosomes.length = max(end(pbnc),
                                                               end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

pbnc_to_smc3a <- GenometriCorrelation(pbnc,
                                      annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                      chromosomes.length = max(end(pbnc),
                                                               end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

pbnc_to_znf143 <- GenometriCorrelation(pbnc,
                                       annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                       chromosomes.length = max(end(pbnc),
                                                                end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                       chromosomes.to.proceed = "chr22", 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)

############################################################################################################

#PAC
sh <- unique(subjectHits(findOverlaps(toptfbs_median_gm12878_chr22[[3]], toptfbs_median_gm12878_chr22[[4]])))
pac <- toptfbs_median_gm12878_chr22[[4]][sh]

pac_to_ctcf <- GenometriCorrelation(pac,
                                    annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                    chromosomes.length = max(end(pac),
                                                             end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                    chromosomes.to.proceed = "chr22", 
                                    permut.number = 100,
                                    ecdf.area.permut.number = 100,
                                    mean.distance.permut.number = 100,
                                    jaccard.measure.permut.number = 100,
                                    keep.distributions = TRUE, 
                                    showProgressBar = TRUE)

pac_to_rad21 <- GenometriCorrelation(pac,
                                     annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                     chromosomes.length = max(end(pac),
                                                              end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pac_to_smc3a <- GenometriCorrelation(pac,
                                     annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                     chromosomes.length = max(end(pac),
                                                              end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pac_to_znf143 <- GenometriCorrelation(pac,
                                      annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                      chromosomes.length = max(end(pac),
                                                               end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

############################################################################################################

#CAP
qh <- unique(queryHits(findOverlaps(toptfbs_median_gm12878_chr22[[3]], toptfbs_median_gm12878_chr22[[4]])))
cap <- toptfbs_median_gm12878_chr22[[3]][qh]

cap_to_ctcf <- GenometriCorrelation(cap,
                                    annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                    chromosomes.length = max(end(cap),
                                                             end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                    chromosomes.to.proceed = "chr22", 
                                    permut.number = 100,
                                    ecdf.area.permut.number = 100,
                                    mean.distance.permut.number = 100,
                                    jaccard.measure.permut.number = 100,
                                    keep.distributions = TRUE, 
                                    showProgressBar = TRUE)

cap_to_rad21 <- GenometriCorrelation(cap,
                                     annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                     chromosomes.length = max(end(cap),
                                                              end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cap_to_smc3a <- GenometriCorrelation(cap,
                                     annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                     chromosomes.length = max(end(cap),
                                                              end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cap_to_znf143 <- GenometriCorrelation(cap,
                                      annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                      chromosomes.length = max(end(cap),
                                                               end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

###########################################################################################################

#CBNP
qh <- unique(queryHits(findOverlaps(toptfbs_median_gm12878_chr22[[3]], toptfbs_median_gm12878_chr22[[4]])))
cbnp <- toptfbs_median_gm12878_chr22[[3]][-qh]

cbnp_to_ctcf <- GenometriCorrelation(cbnp,
                                     annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                     chromosomes.length = max(end(cbnp),
                                                              end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cbnp_to_rad21 <- GenometriCorrelation(cbnp,
                                      annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                      chromosomes.length = max(end(cbnp),
                                                               end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

cbnp_to_smc3a <- GenometriCorrelation(cbnp,
                                      annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                      chromosomes.length = max(end(cbnp),
                                                               end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

cbnp_to_znf143 <- GenometriCorrelation(cbnp,
                                       annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                       chromosomes.length = max(end(cbnp),
                                                                end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                       chromosomes.to.proceed = "chr22", 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)


############################################################################################################


pred_v_called_median_df <- data.frame(AbsoluteDist = c(#PBNC
  pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data,
  pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data,
  
  #PAC
  pac_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  pac_to_rad21@.Data[[1]]$absolute.min.distance.data,
  pac_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  pac_to_znf143@.Data[[1]]$absolute.min.distance.data,
  
  #CAP
  cap_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  cap_to_rad21@.Data[[1]]$absolute.min.distance.data,
  cap_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  cap_to_znf143@.Data[[1]]$absolute.min.distance.data,
  
  #CBNP
  cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data,
  cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data),
  Annotation = c(#PBNC
    rep("CTCF",length(pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #PAC
    rep("CTCF",length(pac_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(pac_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(pac_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(pac_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CAP
    rep("CTCF",length(cap_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(cap_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(cap_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(cap_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CBNP
    rep("CTCF",length(cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data))),
  BoundReg = c(#PBNC
    rep("PBNC", length(pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("PBNC", length(pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("PBNC", length(pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("PBNC", length(pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #PAC
    rep("PAC", length(pac_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("PAC", length(pac_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("PAC", length(pac_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("PAC", length(pac_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CAP
    rep("CAP", length(cap_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("CAP", length(cap_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("CAP", length(cap_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("CAP", length(cap_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #CBNP
    rep("CBNP", length(cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("CBNP", length(cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("CBNP", length(cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("CBNP", length(cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data))))
pred_v_called_median_df$BoundReg <- factor(pred_v_called_median_df$BoundReg, levels=c("PBNC", "PAC", "CAP", "CBNP"))
pred_v_called_median_df$log2AbsoluteDist <- log(pred_v_called_median_df$AbsoluteDist + 1, base = 2)

ggplot(pred_v_called_median_df, aes(x=BoundReg, y = log2AbsoluteDist, fill=BoundReg))  + 
  facet_grid(~ Annotation) +    
  stat_boxplot(geom ='errorbar', width = 0.2) + 
  geom_boxplot(outlier.shape = NA) +
  #stat_compare_means(comparisons = list( c("PBNC", "PAC"), 
  #                                       c("PBNC", "CAP"), 
  #                                       c("PBNC", "CBNP"),
  #                                       c("PAC", "CAP"),
  #                                       c("PAC", "CBNP"),
  #                                       c("CAP", "CBNP")),
  #                   vjust = 0,
  #                   #textsize = 4,
  #                   #size = .5,
  #                   #step_increase = .08, 
  #                   method = "wilcox.test", 
  #                   label = "p.format") +
  geom_signif(test = "wilcox.test", 
            comparisons = list( c("PBNC", "PAC"), 
                                c("PBNC", "CAP"), 
                                c("PBNC", "CBNP"),
                                c("PAC", "CAP"),
                                c("PAC", "CBNP"),
                                c("CAP", "CBNP")),
            vjust = 0,
            textsize = 4,
            size = .5,
            step_increase = .08) +
  theme_minimal()+
  theme_bw()+
  ylab("Log2 Distance to Annotation")+
  xlab("") +
  ggtitle("Median width cutoff")+
  scale_fill_discrete(name="Boundary Region")+
  scale_x_discrete(labels=c("PBNC"="Predicted but\nnot called",
                            "PAC"="Predicted\nand called",
                            "CAP"="Called and\npredicted",
                            "CBNP"="Called but not\npredicted"))+
  #guides(color=FALSE, linetype=FALSE)+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        strip.text.x = element_text(size = 15),
        #panel.spacing = unit(2, "lines"),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        plot.title = element_text(size=20),
        legend.position = "bottom")

```

### Mean length of adjacent 1bp cutoff

```{r}
toptfbs_mean_gm12878_chr22 <- readRDS("Z:/TAD_data_analysis/GM12878/experiments/toptfbs_mean.rds")

venn_cnt2venn <- function(venn_cnt){
  n <- which(colnames(venn_cnt)=="Counts") - 1
  SetNames=colnames(venn_cnt)[1:n]
  Weight=venn_cnt[,"Counts"]
  names(Weight) <- apply(venn_cnt[,1:n], 1, paste, collapse="")
  Venn(SetNames=SetNames, Weight=Weight)
}

res <- makeVennDiagram(Peaks=list(toptfbs_mean_gm12878_chr22[[3]], toptfbs_mean_gm12878_chr22[[4]]),
                       NameOfPeaks=c("Called", "Predicted"),
                       connectedPeaks = "keepAll")
venn_gm12878_22 <- venn_cnt2venn(res$vennCounts)
venn_gm12878_22 <- compute.Venn(venn_gm12878_22)
gp <- VennThemes(venn_gm12878_22)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_5kb, 
                                                 gp = gp, 
                                                 show=list(Universe=FALSE))), 
                        top=textGrob("Boundary Region", 
                                     gp=gpar(fontsize=50)))

############################################################################################################

#PBNC

sh <- unique(subjectHits(findOverlaps(toptfbs_mean_gm12878_chr22[[3]], toptfbs_mean_gm12878_chr22[[4]])))
pbnc <- toptfbs_mean_gm12878_chr22[[4]][-sh]

pbnc_to_ctcf <- GenometriCorrelation(pbnc,
                                     annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                     chromosomes.length = max(end(pbnc),
                                                              end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pbnc_to_rad21 <- GenometriCorrelation(pbnc,
                                      annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                      chromosomes.length = max(end(pbnc),
                                                               end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

pbnc_to_smc3a <- GenometriCorrelation(pbnc,
                                      annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                      chromosomes.length = max(end(pbnc),
                                                               end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

pbnc_to_znf143 <- GenometriCorrelation(pbnc,
                                       annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                       chromosomes.length = max(end(pbnc),
                                                                end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                       chromosomes.to.proceed = "chr22", 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)

############################################################################################################

#PAC
sh <- unique(subjectHits(findOverlaps(toptfbs_mean_gm12878_chr22[[3]], toptfbs_mean_gm12878_chr22[[4]])))
pac <- toptfbs_mean_gm12878_chr22[[4]][sh]

pac_to_ctcf <- GenometriCorrelation(pac,
                                    annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                    chromosomes.length = max(end(pac),
                                                             end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                    chromosomes.to.proceed = "chr22", 
                                    permut.number = 100,
                                    ecdf.area.permut.number = 100,
                                    mean.distance.permut.number = 100,
                                    jaccard.measure.permut.number = 100,
                                    keep.distributions = TRUE, 
                                    showProgressBar = TRUE)

pac_to_rad21 <- GenometriCorrelation(pac,
                                     annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                     chromosomes.length = max(end(pac),
                                                              end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pac_to_smc3a <- GenometriCorrelation(pac,
                                     annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                     chromosomes.length = max(end(pac),
                                                              end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

pac_to_znf143 <- GenometriCorrelation(pac,
                                      annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                      chromosomes.length = max(end(pac),
                                                               end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

############################################################################################################

#CAP
qh <- unique(queryHits(findOverlaps(toptfbs_mean_gm12878_chr22[[3]], toptfbs_mean_gm12878_chr22[[4]])))
cap <- toptfbs_mean_gm12878_chr22[[3]][qh]

cap_to_ctcf <- GenometriCorrelation(cap,
                                    annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                    chromosomes.length = max(end(cap),
                                                             end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                    chromosomes.to.proceed = "chr22", 
                                    permut.number = 100,
                                    ecdf.area.permut.number = 100,
                                    mean.distance.permut.number = 100,
                                    jaccard.measure.permut.number = 100,
                                    keep.distributions = TRUE, 
                                    showProgressBar = TRUE)

cap_to_rad21 <- GenometriCorrelation(cap,
                                     annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                     chromosomes.length = max(end(cap),
                                                              end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cap_to_smc3a <- GenometriCorrelation(cap,
                                     annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                     chromosomes.length = max(end(cap),
                                                              end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cap_to_znf143 <- GenometriCorrelation(cap,
                                      annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                      chromosomes.length = max(end(cap),
                                                               end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

###########################################################################################################

#CBNP
qh <- unique(queryHits(findOverlaps(toptfbs_mean_gm12878_chr22[[3]], toptfbs_mean_gm12878_chr22[[4]])))
cbnp <- toptfbs_mean_gm12878_chr22[[3]][-qh]

cbnp_to_ctcf <- GenometriCorrelation(cbnp,
                                     annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"], 
                                     chromosomes.length = max(end(cbnp),
                                                              end(annots.GR[[1]][seqnames(annots.GR[[1]])=="chr22"])),
                                     chromosomes.to.proceed = "chr22", 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

cbnp_to_rad21 <- GenometriCorrelation(cbnp,
                                      annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"], 
                                      chromosomes.length = max(end(cbnp),
                                                               end(annots.GR[[2]][seqnames(annots.GR[[2]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

cbnp_to_smc3a <- GenometriCorrelation(cbnp,
                                      annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"], 
                                      chromosomes.length = max(end(cbnp),
                                                               end(annots.GR[[3]][seqnames(annots.GR[[3]])=="chr22"])),
                                      chromosomes.to.proceed = "chr22", 
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

cbnp_to_znf143 <- GenometriCorrelation(cbnp,
                                       annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"], 
                                       chromosomes.length = max(end(cbnp),
                                                                end(annots.GR[[4]][seqnames(annots.GR[[4]])=="chr22"])),
                                       chromosomes.to.proceed = "chr22", 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)


############################################################################################################


pred_v_called_mean_df <- data.frame(AbsoluteDist = c(#PBNC
                                            pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data,
                                            pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data,
                                            pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data,
                                            pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data,
                                            
                                            #PAC
                                            pac_to_ctcf@.Data[[1]]$absolute.min.distance.data,
                                            pac_to_rad21@.Data[[1]]$absolute.min.distance.data,
                                            pac_to_smc3a@.Data[[1]]$absolute.min.distance.data,
                                            pac_to_znf143@.Data[[1]]$absolute.min.distance.data,
                                            
                                            #CAP
                                            cap_to_ctcf@.Data[[1]]$absolute.min.distance.data,
                                            cap_to_rad21@.Data[[1]]$absolute.min.distance.data,
                                            cap_to_smc3a@.Data[[1]]$absolute.min.distance.data,
                                            cap_to_znf143@.Data[[1]]$absolute.min.distance.data,
                                            
                                            #CBNP
                                            cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data,
                                            cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data,
                                            cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data,
                                            cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data),
                               Annotation = c(#PBNC
                                            rep("CTCF",length(pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("RAD21",length(pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("SMC3a",length(pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("ZNF143",length(pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data)),
                                            
                                            #PAC
                                            rep("CTCF",length(pac_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("RAD21",length(pac_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("SMC3a",length(pac_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("ZNF143",length(pac_to_znf143@.Data[[1]]$absolute.min.distance.data)),
                                            
                                            #CAP
                                            rep("CTCF",length(cap_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("RAD21",length(cap_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("SMC3a",length(cap_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("ZNF143",length(cap_to_znf143@.Data[[1]]$absolute.min.distance.data)),
                                            
                                            #CBNP
                                            rep("CTCF",length(cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("RAD21",length(cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("SMC3a",length(cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("ZNF143",length(cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data))),
                               BoundReg = c(#PBNC
                                            rep("PBNC", length(pbnc_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("PBNC", length(pbnc_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("PBNC", length(pbnc_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("PBNC", length(pbnc_to_znf143@.Data[[1]]$absolute.min.distance.data)),
                                            
                                            #PAC
                                            rep("PAC", length(pac_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("PAC", length(pac_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("PAC", length(pac_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("PAC", length(pac_to_znf143@.Data[[1]]$absolute.min.distance.data)),
                                            
                                            #CAP
                                            rep("CAP", length(cap_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("CAP", length(cap_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("CAP", length(cap_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("CAP", length(cap_to_znf143@.Data[[1]]$absolute.min.distance.data)),
                                            
                                            #CBNP
                                            rep("CBNP", length(cbnp_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
                                            rep("CBNP", length(cbnp_to_rad21@.Data[[1]]$absolute.min.distance.data)),
                                            rep("CBNP", length(cbnp_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
                                            rep("CBNP", length(cbnp_to_znf143@.Data[[1]]$absolute.min.distance.data))))
pred_v_called_mean_df$BoundReg <- factor(pred_v_called_mean_df$BoundReg, levels=c("PBNC", "PAC", "CAP", "CBNP"))
pred_v_called_mean_df$log2AbsoluteDist <- log(pred_v_called_mean_df$AbsoluteDist + 1, base = 2)

ggplot(pred_v_called_mean_df, aes(x=BoundReg, y = log2AbsoluteDist, fill=BoundReg))  + 
  facet_grid(~ Annotation) +    
  stat_boxplot(geom ='errorbar', width = 0.2) + 
  geom_boxplot(outlier.shape = NA) +
  #stat_compare_means(comparisons = list( c("PBNC", "PAC"), 
  #                                       c("PBNC", "CAP"), 
  #                                       c("PBNC", "CBNP"),
  #                                       c("PAC", "CAP"),
  #                                       c("PAC", "CBNP"),
  #                                       c("CAP", "CBNP")),
  #                   vjust = 0,
  #                   #textsize = 4,
  #                   #size = .5,
  #                   #step_increase = .08, 
  #                   method = "wilcox.test", 
  #                   label = "p.format") +
  geom_signif(test = "wilcox.test", 
            comparisons = list( c("PBNC", "PAC"), 
                                c("PBNC", "CAP"), 
                                c("PBNC", "CBNP"),
                                c("PAC", "CAP"),
                                c("PAC", "CBNP"),
                                c("CAP", "CBNP")),
            vjust = 0,
            textsize = 4,
            size = .5,
            step_increase = .08) +
  theme_minimal()+
  theme_bw()+
  ylab("Log2 Distance to Annotation")+
  xlab("") +
  ggtitle("Mean width cutoff")+
  scale_fill_discrete(name="Boundary Region")+
  scale_x_discrete(labels=c("PBNC"="Predicted but\nnot called",
                            "PAC"="Predicted\nand called",
                            "CAP"="Called and\npredicted",
                            "CBNP"="Called but not\npredicted"))+
  #guides(color=FALSE, linetype=FALSE)+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        strip.text.x = element_text(size = 15),
        #panel.spacing = unit(2, "lines"),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        plot.title = element_text(size=20),
        legend.position = "bottom")

```


