---
title: "Investigating TFBS Specific Model Performances"
author: "Spiro Stilianoudakis"
date: "April 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)

```


# GM12878; smote; distance types

## 10kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_10kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_10kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_10kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_gm12878_10kb_smote_dist <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```

## 25kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_25kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_25kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_25kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_gm12878_25kb_smote_dist <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```


## 50kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_50kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_50kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_50kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_gm12878_50kb_smote_dist <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```

## 100kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_100kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_100kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_gm12878_100kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_gm12878_100kb_smote_dist <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```

# Plots

```{r}
all_rfperfs_gm12878 <- data.frame(Annotation=rep(c("TFBS", 
                                               "Chromatin State Segmentations", 
                                               "Histone Modifications", 
                                               "All Combined"), 8),
                                  Resolution=rep(c(rep("10 kb", 4),
                                               rep("25 kb", 4),
                                               rep("50 kb", 4),
                                               rep("100 kb", 4)), 2),
                                  Metric=c(rep("F1-Score", 16),
                                           rep("MCC", 16))
                                  )
all_rfperfs_gm12878$Annotation <- factor(all_rfperfs_gm12878$Annotation, levels=c("Histone Modifications",
                                                                                  "Chromatin State Segmentations",
                                                                                  "TFBS",
                                                                                  "All Combined"))
all_rfperfs_gm12878$Resolution <- factor(all_rfperfs_gm12878$Resolution, levels=c("10 kb", "25 kb", "50 kb", "100 kb"))
all_rfperfs_gm12878$Metric <- factor(all_rfperfs_gm12878$Metric, levels=c("F1-Score", "MCC"))

all_rfperfs_gm12878$Performance <- c(rfperf_gm12878_10kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_gm12878_10kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_gm12878_10kb_smote_dist_histones[16,2], #f1
                                     rfperf_gm12878_10kb_smote_dist[16,2], #f1
                                     
                                     rfperf_gm12878_25kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_gm12878_25kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_gm12878_25kb_smote_dist_histones[16,2], #f1
                                     rfperf_gm12878_25kb_smote_dist[16,2], #f1
                                     
                                     rfperf_gm12878_50kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_gm12878_50kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_gm12878_50kb_smote_dist_histones[16,2], #f1
                                     rfperf_gm12878_50kb_smote_dist[16,2], #f1
                                     
                                     rfperf_gm12878_100kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_gm12878_100kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_gm12878_100kb_smote_dist_histones[16,2], #f1
                                     rfperf_gm12878_100kb_smote_dist[16,2], #f1
                                     
                                     rfperf_gm12878_10kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_gm12878_10kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_gm12878_10kb_smote_dist_histones[15,2], #mcc
                                     rfperf_gm12878_10kb_smote_dist[15,2], #mcc
                                     
                                     rfperf_gm12878_25kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_gm12878_25kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_gm12878_25kb_smote_dist_histones[15,2], #mcc
                                     rfperf_gm12878_25kb_smote_dist[15,2], #mcc
                                     
                                     rfperf_gm12878_50kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_gm12878_50kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_gm12878_50kb_smote_dist_histones[15,2], #mcc
                                     rfperf_gm12878_50kb_smote_dist[15,2], #mcc
                                     
                                     rfperf_gm12878_100kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_gm12878_100kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_gm12878_100kb_smote_dist_histones[15,2], #mcc
                                     rfperf_gm12878_100kb_smote_dist[15,2] #mcc
                                     )

ggplot(all_rfperfs_gm12878,
       aes(x=Resolution, y=Performance, fill=Annotation)) +
  geom_bar( stat="identity", position="dodge") +
  facet_grid( ~ Metric) +
  #xlab("") + ylab("") +
  theme_minimal() +
  theme_bw() +
  scale_fill_discrete(name="Category of\nFeature Space",
                      labels=c("Histone\nModifications",
                               "Chromatin State\nSegmentations",
                               "Transcription Factor\nBinding Sites",
                               "All Combined"))+
  #guides(fill=FALSE)+
  theme(axis.text.x = element_text(size=15,
                                   angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   hjust = 1),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))
```


# K562; smote; distance types

## 10kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_10kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/K562/10kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_10kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/K562/10kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_10kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/K562/10kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_K562_10kb_smote_dist <- readRDS("Z:/TAD_data_analysis/K562/10kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```

## 25kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_25kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/K562/25kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_25kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/K562/25kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_25kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/K562/25kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_K562_25kb_smote_dist <- readRDS("Z:/TAD_data_analysis/K562/25kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```


## 50kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_50kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/K562/50kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_50kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/K562/50kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_50kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/K562/50kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_K562_50kb_smote_dist <- readRDS("Z:/TAD_data_analysis/K562/50kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```

## 100kb

```{r}
### TFBS Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_100kb_smote_dist_tfbs <- readRDS("Z:/TAD_data_analysis/K562/100kb/Ensemble/SMOTE/tfbs/Distance/ENET/RF/rfperf.rds")

### Chromstates Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_100kb_smote_dist_chromstates <- readRDS("Z:/TAD_data_analysis/K562/100kb/Ensemble/SMOTE/chromstates/Distance/ENET/RF/rfperf.rds")

### Histones Specific Model Performances
####SMOTE
#####Distance
rfperf_K562_100kb_smote_dist_histones <- readRDS("Z:/TAD_data_analysis/K562/100kb/Ensemble/SMOTE/histones/Distance/ENET/RF/rfperf.rds")

### All Annotations
####SMOTE
#####Distance
rfperf_K562_100kb_smote_dist <- readRDS("Z:/TAD_data_analysis/K562/100kb/Ensemble/SMOTE/Distance/ENET/RF/rfperf.rds")

```

# Plots

```{r}
all_rfperfs_K562 <- data.frame(Annotation=rep(c("TFBS", 
                                               "Chromatin State Segmentations", 
                                               "Histone Modifications", 
                                               "All Combined"), 8),
                                  Resolution=rep(c(rep("10 kb", 4),
                                               rep("25 kb", 4),
                                               rep("50 kb", 4),
                                               rep("100 kb", 4)), 2),
                                  Metric=c(rep("F1-Score", 16),
                                           rep("MCC", 16))
                                  )
all_rfperfs_K562$Annotation <- factor(all_rfperfs_K562$Annotation, levels=c("Histone Modifications",
                                                                                  "Chromatin State Segmentations",
                                                                                  "TFBS",
                                                                                  "All Combined"))
all_rfperfs_K562$Resolution <- factor(all_rfperfs_K562$Resolution, levels=c("10 kb", "25 kb", "50 kb", "100 kb"))
all_rfperfs_K562$Metric <- factor(all_rfperfs_K562$Metric, levels=c("F1-Score", "MCC"))

all_rfperfs_K562$Performance <- c(rfperf_K562_10kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_K562_10kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_K562_10kb_smote_dist_histones[16,2], #f1
                                     rfperf_K562_10kb_smote_dist[16,2], #f1
                                     
                                     rfperf_K562_25kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_K562_25kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_K562_25kb_smote_dist_histones[16,2], #f1
                                     rfperf_K562_25kb_smote_dist[16,2], #f1
                                     
                                     rfperf_K562_50kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_K562_50kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_K562_50kb_smote_dist_histones[16,2], #f1
                                     rfperf_K562_50kb_smote_dist[16,2], #f1
                                     
                                     rfperf_K562_100kb_smote_dist_tfbs[16,2], #f1
                                     rfperf_K562_100kb_smote_dist_chromstates[16,2], #f1
                                     rfperf_K562_100kb_smote_dist_histones[16,2], #f1
                                     rfperf_K562_100kb_smote_dist[16,2], #f1
                                     
                                     rfperf_K562_10kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_K562_10kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_K562_10kb_smote_dist_histones[15,2], #mcc
                                     rfperf_K562_10kb_smote_dist[15,2], #mcc
                                     
                                     rfperf_K562_25kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_K562_25kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_K562_25kb_smote_dist_histones[15,2], #mcc
                                     rfperf_K562_25kb_smote_dist[15,2], #mcc
                                     
                                     rfperf_K562_50kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_K562_50kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_K562_50kb_smote_dist_histones[15,2], #mcc
                                     rfperf_K562_50kb_smote_dist[15,2], #mcc
                                     
                                     rfperf_K562_100kb_smote_dist_tfbs[15,2], #mcc
                                     rfperf_K562_100kb_smote_dist_chromstates[15,2], #mcc
                                     rfperf_K562_100kb_smote_dist_histones[15,2], #mcc
                                     rfperf_K562_100kb_smote_dist[15,2] #mcc
                                     )

ggplot(all_rfperfs_K562,
       aes(x=Resolution, y=Performance, fill=Annotation)) +
  geom_bar( stat="identity", position="dodge") +
  facet_grid( ~ Metric) +
  #xlab("") + ylab("") +
  theme_minimal() +
  theme_bw() +
  scale_fill_discrete(name="Category of\nFeature Space",
                      labels=c("Histone\nModifications",
                               "Chromatin State\nSegmentations",
                               "Transcription Factor\nBinding Sites",
                               "All Combined"))+
  #guides(fill=FALSE)+
  theme(axis.text.x = element_text(size=15,
                                   angle = 45, 
                                   #margin = ggplot2::margin(t = 35),
                                   hjust = 1),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        strip.text.x = element_text(size = 15))
```

