---
title: "Untitled"
author: "Spiro Stilianoudakis"
date: "June 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)
library(Vennerable)
library(ChIPpeakAnno)
```

# Comparing TAD regions across cell lines

## Function to extract boundaries

```{r}
source("C:/Users/stili/Documents/TAD_predictive_modeling/Scripts/functions_for_R_package/extract_boundaries_func.r")
```

## Venn diagrams

```{r}
venn_cnt2venn <- function(venn_cnt){
  n <- which(colnames(venn_cnt)=="Counts") - 1
  SetNames=colnames(venn_cnt)[1:n]
  Weight=venn_cnt[,"Counts"]
  names(Weight) <- apply(venn_cnt[,1:n], 1, paste, collapse="")
  Venn(SetNames=SetNames, Weight=Weight)
}

```

### 5kb

```{r}
#bounds_f_gm12878_5kb <- readRDS("Z:/TAD_data_analysis/GM12878/5kb/training_testing/bounds_f.rds")
#bounds_f_K562_5kb <- readRDS("Z:/TAD_data_analysis/K562/5kb/training_testing/bounds_f.rds")

#res <- makeVennDiagram(Peaks=list(bounds_f_gm12878_5kb, bounds_f_K562_5kb),
#                       NameOfPeaks=c("GM12878", "K562"))

#venn_5kb <- venn_cnt2venn(res$vennCounts)
#plot(venn_5kb)

#binslist_gm12878_5kb <- readRDS("Z:/TAD_data_analysis/GM12878/5kb/training_testing/binslist5.rds")
#binslist_gm12878_5kb_center <- readRDS("Z:/TAD_data_analysis/GM12878/5kb/training_testing/binslist5_center.rds")
#mcols(binslist_gm12878_5kb)$y <- mcols(binslist_gm12878_5kb_center)$y
#binslist_gm12878_5kb <- binslist_gm12878_5kb[mcols(binslist_gm12878_5kb)$y==1]

#binslist_K562_5kb <- readRDS("Z:/TAD_data_analysis/K562/5kb/training_testing/binslist5.rds")
#binslist_K562_5kb_center <- readRDS("Z:/TAD_data_analysis/K562/5kb/training_testing/binslist5_center.rds")
#mcols(binslist_K562_5kb)$y <- mcols(binslist_K562_5kb_center)$y
#binslist_K562_5kb <- binslist_K562_5kb[mcols(binslist_K562_5kb)$y==1]

#bounds_gm12878_5kb <- readRDS("Z:/TAD_data_analysis/GM12878/5kb/training_testing/bounds_f.rds")
#bounds_k562_5kb <- readRDS("Z:/TAD_data_analysis/K562/5kb/training_testing/bounds_f.rds")

domains <- read.table("Z:/TAD_data_analysis/GM12878/5kb/GM12878_domain_data_5000.b.txt", header=F)
bounds_gm12878_5kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=5000)
  bounds_gm12878_5kb[[i]] <- bounds
}
bounds_gm12878_5kb <- do.call("c", bounds_gm12878_5kb)

domains <- read.table("Z:/TAD_data_analysis/K562/5kb/K562_domain_data_5000.b.txt", header=F)
bounds_k562_5kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=5000)
  bounds_k562_5kb[[i]] <- bounds
}
bounds_k562_5kb <- do.call("c", bounds_k562_5kb)

res <- makeVennDiagram(Peaks=list(bounds_gm12878_5kb, bounds_k562_5kb),
                       NameOfPeaks=c("GM12878", "K562"))

venn_5kb <- venn_cnt2venn(res$vennCounts)
venn_5kb <- compute.Venn(venn_5kb)
gp <- VennThemes(venn_5kb)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2

#plot(venn_5kb)

```

### 10kb

```{r}
#bounds_f_gm12878_10kb <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/training_testing/bounds_f.rds")
#bounds_f_K562_10kb <- readRDS("Z:/TAD_data_analysis/K562/10kb/training_testing/bounds_f.rds")

#res <- makeVennDiagram(Peaks=list(bounds_f_gm12878_10kb, bounds_f_K562_10kb),
#                       NameOfPeaks=c("GM12878", "K562"))

#venn_10kb <- venn_cnt2venn(res$vennCounts)
#plot(venn_10kb)

#binslist_gm12878_10kb <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/training_testing/binslist10.rds")
#binslist_gm12878_10kb_center <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/training_testing/binslist10_center.rds")
#mcols(binslist_gm12878_10kb)$y <- mcols(binslist_gm12878_10kb_center)$y
#binslist_gm12878_10kb <- binslist_gm12878_10kb[mcols(binslist_gm12878_10kb)$y==1]

#binslist_K562_10kb <- readRDS("Z:/TAD_data_analysis/K562/10kb/training_testing/binslist10.rds")
#binslist_K562_10kb_center <- readRDS("Z:/TAD_data_analysis/K562/10kb/training_testing/binslist10_center.rds")
#mcols(binslist_K562_10kb)$y <- mcols(binslist_K562_10kb_center)$y
#binslist_K562_10kb <- binslist_K562_10kb[mcols(binslist_K562_10kb)$y==1]

#bounds_gm12878_10kb <- readRDS("Z:/TAD_data_analysis/GM12878/10kb/training_testing/bounds_f.rds")
#bounds_k562_10kb <- readRDS("Z:/TAD_data_analysis/K562/10kb/training_testing/bounds_f.rds")

domains <- read.table("Z:/TAD_data_analysis/GM12878/10kb/GM12878_domain_data_10000.b.txt", header=F)
bounds_gm12878_10kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=10000)
  bounds_gm12878_10kb[[i]] <- bounds
}
bounds_gm12878_10kb <- do.call("c", bounds_gm12878_10kb)

domains <- read.table("Z:/TAD_data_analysis/K562/10kb/K562_domain_data_10000.b.txt", header=F)
bounds_k562_10kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=10000)
  bounds_k562_10kb[[i]] <- bounds
}
bounds_k562_10kb <- do.call("c", bounds_k562_10kb)

res <- makeVennDiagram(Peaks=list(bounds_gm12878_10kb, bounds_k562_10kb),
                       NameOfPeaks=c("GM12878", "K562"))


venn_10kb <- venn_cnt2venn(res$vennCounts)
venn_10kb <- compute.Venn(venn_10kb)
gp <- VennThemes(venn_10kb)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
#plot(venn_10kb)

```

### 25kb

```{r}
#bounds_f_gm12878_25kb <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/training_testing/bounds_f.rds")
#bounds_f_K562_25kb <- readRDS("Z:/TAD_data_analysis/K562/25kb/training_testing/bounds_f.rds")

#res <- makeVennDiagram(Peaks=list(bounds_f_gm12878_25kb, bounds_f_K562_25kb),
#                       NameOfPeaks=c("GM12878", "K562"))

#venn_25kb <- venn_cnt2venn(res$vennCounts)
#plot(venn_25kb)

#binslist_gm12878_25kb <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/training_testing/binslist25.rds")
#binslist_gm12878_25kb_center <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/training_testing/binslist25_center.rds")
#mcols(binslist_gm12878_25kb)$y <- mcols(binslist_gm12878_25kb_center)$y
#binslist_gm12878_25kb <- binslist_gm12878_25kb[mcols(binslist_gm12878_25kb)$y==1]

#binslist_K562_25kb <- readRDS("Z:/TAD_data_analysis/K562/25kb/training_testing/binslist25.rds")
#binslist_K562_25kb_center <- readRDS("Z:/TAD_data_analysis/K562/25kb/training_testing/binslist25_center.rds")
#mcols(binslist_K562_25kb)$y <- mcols(binslist_K562_25kb_center)$y
#binslist_K562_25kb <- binslist_K562_25kb[mcols(binslist_K562_25kb)$y==1]

#bounds_gm12878_25kb <- readRDS("Z:/TAD_data_analysis/GM12878/25kb/training_testing/bounds_f.rds")
#bounds_k562_25kb <- readRDS("Z:/TAD_data_analysis/K562/25kb/training_testing/bounds_f.rds")

domains <- read.table("Z:/TAD_data_analysis/GM12878/25kb/GM12878_domain_data_25000.b.txt", header=F)
bounds_gm12878_25kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=25000)
  bounds_gm12878_25kb[[i]] <- bounds
}
bounds_gm12878_25kb <- do.call("c", bounds_gm12878_25kb)

domains <- read.table("Z:/TAD_data_analysis/K562/25kb/K562_domain_data_25000.b.txt", header=F)
bounds_k562_25kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=25000)
  bounds_k562_25kb[[i]] <- bounds
}
bounds_k562_25kb <- do.call("c", bounds_k562_25kb)

res <- makeVennDiagram(Peaks=list(bounds_gm12878_25kb, bounds_k562_25kb),
                       NameOfPeaks=c("GM12878", "K562"))


venn_25kb <- venn_cnt2venn(res$vennCounts)
venn_25kb <- compute.Venn(venn_25kb)
gp <- VennThemes(venn_25kb)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
#plot(venn_25kb)

```

### 50kb

```{r}
#bounds_f_gm12878_50kb <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/training_testing/bounds_f.rds")
#bounds_f_K562_50kb <- readRDS("Z:/TAD_data_analysis/K562/50kb/training_testing/bounds_f.rds")

#res <- makeVennDiagram(Peaks=list(bounds_f_gm12878_50kb, bounds_f_K562_50kb),
#                       NameOfPeaks=c("GM12878", "K562"))

#venn_50kb <- venn_cnt2venn(res$vennCounts)
#plot(venn_50kb)

#binslist_gm12878_50kb <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/training_testing/binslist50.rds")
#binslist_gm12878_50kb_center <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/training_testing/binslist50_center.rds")
#mcols(binslist_gm12878_50kb)$y <- mcols(binslist_gm12878_50kb_center)$y
#binslist_gm12878_50kb <- binslist_gm12878_50kb[mcols(binslist_gm12878_50kb)$y==1]

#binslist_K562_50kb <- readRDS("Z:/TAD_data_analysis/K562/50kb/training_testing/binslist50.rds")
#binslist_K562_50kb_center <- readRDS("Z:/TAD_data_analysis/K562/50kb/training_testing/binslist50_center.rds")
#mcols(binslist_K562_50kb)$y <- mcols(binslist_K562_50kb_center)$y
#binslist_K562_50kb <- binslist_K562_50kb[mcols(binslist_K562_50kb)$y==1]

#bounds_gm12878_50kb <- readRDS("Z:/TAD_data_analysis/GM12878/50kb/training_testing/bounds_f.rds")
#bounds_k562_50kb <- readRDS("Z:/TAD_data_analysis/K562/50kb/training_testing/bounds_f.rds")

domains <- read.table("Z:/TAD_data_analysis/GM12878/50kb/GM12878_domain_data_50000.b.txt", header=F)
bounds_gm12878_50kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=50000)
  bounds_gm12878_50kb[[i]] <- bounds
}
bounds_gm12878_50kb <- do.call("c", bounds_gm12878_50kb)

domains <- read.table("Z:/TAD_data_analysis/K562/50kb/K562_domain_data_50000.b.txt", header=F)
bounds_k562_50kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=50000)
  bounds_k562_50kb[[i]] <- bounds
}
bounds_k562_50kb <- do.call("c", bounds_k562_50kb)

res <- makeVennDiagram(Peaks=list(bounds_gm12878_50kb, bounds_k562_50kb),
                       NameOfPeaks=c("GM12878", "K562"))


venn_50kb <- venn_cnt2venn(res$vennCounts)
venn_50kb <- compute.Venn(venn_50kb)
gp <- VennThemes(venn_50kb)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
#plot(venn_50kb)

```

### 100kb

```{r}
#bounds_f_gm12878_100kb <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/training_testing/bounds_f.rds")
#bounds_f_K562_100kb <- readRDS("Z:/TAD_data_analysis/K562/100kb/training_testing/bounds_f.rds")

#res <- makeVennDiagram(Peaks=list(bounds_f_gm12878_100kb, bounds_f_K562_100kb),
#                       NameOfPeaks=c("GM12878", "K562"))

#venn_100kb <- venn_cnt2venn(res$vennCounts)
#plot(venn_100kb)

#binslist_gm12878_100kb <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/training_testing/binslist100.rds")
#binslist_gm12878_100kb_center <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/training_testing/binslist100_center.rds")
#mcols(binslist_gm12878_100kb)$y <- mcols(binslist_gm12878_100kb_center)$y
#binslist_gm12878_100kb <- binslist_gm12878_100kb[mcols(binslist_gm12878_100kb)$y==1]

#binslist_K562_100kb <- readRDS("Z:/TAD_data_analysis/K562/100kb/training_testing/binslist100.rds")
#binslist_K562_100kb_center <- readRDS("Z:/TAD_data_analysis/K562/100kb/training_testing/binslist100_center.rds")
#mcols(binslist_K562_100kb)$y <- mcols(binslist_K562_100kb_center)$y
#binslist_K562_100kb <- binslist_K562_100kb[mcols(binslist_K562_100kb)$y==1]

#bounds_gm12878_100kb <- readRDS("Z:/TAD_data_analysis/GM12878/100kb/training_testing/bounds_f.rds")
#bounds_k562_100kb <- readRDS("Z:/TAD_data_analysis/K562/100kb/training_testing/bounds_f.rds")

domains <- read.table("Z:/TAD_data_analysis/GM12878/100kb/GM12878_domain_data_100000.b.txt", header=F)
bounds_gm12878_100kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=100000)
  bounds_gm12878_100kb[[i]] <- bounds
}
bounds_gm12878_100kb <- do.call("c", bounds_gm12878_100kb)

domains <- read.table("Z:/TAD_data_analysis/K562/100kb/K562_domain_data_100000.b.txt", header=F)
bounds_k562_100kb <- GRangesList()
chrs <- paste0("CHR", c(1:8,10:22))
for(i in 1:length(chrs)){
  bounds <- extract_boundaries_func(domains.mat=domains, preprocess=TRUE, chromosome=chrs[i], resolution=100000)
  bounds_k562_100kb[[i]] <- bounds
}
bounds_k562_100kb <- do.call("c", bounds_k562_100kb)

res <- makeVennDiagram(Peaks=list(bounds_gm12878_100kb, bounds_k562_100kb),
                       NameOfPeaks=c("GM12878", "K562"))


venn_100kb <- venn_cnt2venn(res$vennCounts)
venn_100kb <- compute.Venn(venn_100kb)
gp <- VennThemes(venn_100kb)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
#plot(venn_100kb)

```

### Plots

```{r}
#par(mfrow=c(1,4))

gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_5kb, gp = gp, show=list(Universe=FALSE))), top=textGrob("5 kb", gp=gpar(fontsize=50)))
grid.newpage()
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_10kb, gp = gp, show=list(Universe=FALSE))), top=textGrob("10 kb", gp=gpar(fontsize=50)))
grid.newpage()
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_25kb, gp = gp, show=list(Universe=FALSE))), top=textGrob("25 kb", gp=gpar(fontsize=50)))
grid.newpage()
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_50kb, gp = gp, show=list(Universe=FALSE))), top=textGrob("50 kb", gp=gpar(fontsize=50)))
grid.newpage()
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_100kb, gp = gp, show=list(Universe=FALSE))), top=textGrob("100 kb", gp=gpar(fontsize=50)))


#par(mfrow=c(1,1))
```

