---
title: "Comparing Predicted Boundaries vs Called Boundaries"
author: "Spiro Stilianoudakis"
date: "August 8, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(scales)
library(GGally)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)
library(GenometriCorr)
library(ggpubr)
library(ggsignif)
library(Vennerable)
library(VennDiagram)
library(ChIPpeakAnno)
library(EnrichedHeatmap)
```

# GM12878

## Create granges from top tfbs

```{r}
source("C:/Users/stili/Documents/TAD_predictive_modeling/Scripts/functions_for_R_package/annots_to_granges_func.r")
#file_path="Z:/TAD_data_analysis/annotations/all_common_annotations/gm12878/chr22_tfbs_gm12878"
file_path="Z:/TAD_data_analysis/annotations/all_common_annotations/gm12878/topTFBS"
annots.GR <- annots_to_granges_func(filepath=file_path)

```


## Overlap between Called Regions and Predicted Boundaroes

```{r}

pred_bound_list <- GRangesList()
true_bound_list <- GRangesList()
chrs <- paste0("CHR", c(17:22))
for(i in 1:length(chrs)){
  called_and_pred <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/",
                                    chrs[i],
                                    "/smote/distance/enet/called_and_pred_bound_regions.rds"))
  
  true_bound_list[[i]] <- called_and_pred[[3]]
  pred_bound_list[[i]] <- called_and_pred[[4]]
  
}

all_true_bounds <- do.call("c", true_bound_list)
all_pred_bounds <- do.call("c", pred_bound_list)

venn_cnt2venn <- function(venn_cnt){
  n <- which(colnames(venn_cnt)=="Counts") - 1
  SetNames=colnames(venn_cnt)[1:n]
  Weight=venn_cnt[,"Counts"]
  names(Weight) <- apply(venn_cnt[,1:n], 1, paste, collapse="")
  Venn(SetNames=SetNames, Weight=Weight)
}

res <- makeVennDiagram(Peaks=list(all_true_bounds, all_pred_bounds),
                       NameOfPeaks=c("Called", "Predicted"),
                       connectedPeaks = "keepAll")
venn_gm12878 <- venn_cnt2venn(res$vennCounts)
venn_gm12878 <- compute.Venn(venn_gm12878)
gp <- VennThemes(venn_gm12878)
gp[["Face"]][["11"]]$fill <-  "purple"
gp[["Face"]][["01"]]$fill <-  "lightblue"
gp[["Face"]][["10"]]$fill <-  "red"
gp[["FaceText"]][["10"]]$cex <- 2
gp[["FaceText"]][["11"]]$cex <- 2
gp[["FaceText"]][["01"]]$cex <- 2
gp[["SetText"]][["Set1"]]$cex <- 2
gp[["SetText"]][["Set2"]]$cex <- 2
gridExtra::grid.arrange(grid::grid.grabExpr(plot(venn_gm12878, 
                                                 gp = gp, 
                                                 show=list(Universe=FALSE))), 
                        top=textGrob("Boundary Region", 
                                     gp=gpar(fontsize=50)))


```


## Enriched Heatmaps

```{r}
annots.GR.f <- lapply(annots.GR, function(x){x[which(as.character(seqnames(x)) %in% tolower(chrs))]})

all_true_bounds_r <- resize(all_true_bounds, width=1,fix = "center")

e = 10000
axis_names <- c("-10 kb", "Center", "10 kb")
```

### CTCF

#### Predicted

```{r}

mat = normalizeToMatrix(annots.GR.f[[1]], 
                         all_pred_bounds, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "CTCF"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Predicted", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "left")))
```

#### Called

```{r}

mat = normalizeToMatrix(annots.GR.f[[1]], 
                         all_true_bounds_r, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "CTCF"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Called", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "right")))
```

### RAD21

#### Predicted

```{r}

mat = normalizeToMatrix(annots.GR.f[[2]], 
                         all_pred_bounds, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "RAD21"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Predicted", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "left")))
```

#### Called

```{r}

mat = normalizeToMatrix(annots.GR.f[[2]], 
                         all_true_bounds_r, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "RAD21"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Called", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "right")))
```

### SMC3

#### Predicted

```{r}

mat = normalizeToMatrix(annots.GR.f[[3]], 
                         all_pred_bounds, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "SMC3"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Predicted", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "left")))
```

#### Called

```{r}

mat = normalizeToMatrix(annots.GR.f[[3]], 
                         all_true_bounds_r, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "SMC3"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Called", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "right")))
```

### ZNF143

#### Predicted

```{r}

mat = normalizeToMatrix(annots.GR.f[[4]], 
                         all_pred_bounds, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "ZNF143"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Predicted", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "left")))
```

#### Called

```{r}

mat = normalizeToMatrix(annots.GR.f[[4]], 
                         all_true_bounds_r, 
                         value_column = "coverage", 
                         extend = e, 
                         mean_mode = "w0",
                         keep = c(0,.99))

EnrichedHeatmap(mat, 
                col = c("white", muted("red")), 
                heatmap_legend_param = list(title = "ZNF143"),
                row_title="Chromosomes",
                row_title_side="left", 
                column_title="Called", 
                axis_name = axis_names,
                top_annotation = HeatmapAnnotation(lines = anno_enriched(gp = gpar(col = "red"), 
                                                                         yaxis_side = "right", 
                                                                         yaxis_facing = "right")))
```

## Distance Plots

### Predicted

```{r}
chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_pred_bounds[which(as.character(seqnames(all_pred_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[1]][which(as.character(seqnames(annots.GR.f[[1]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

p_to_ctcf <- GenometriCorrelation(all_pred_bounds,
                                     annots.GR.f[[1]], 
                                     chromosomes.length = chromslength,
                                     chromosomes.to.proceed = tolower(chrs), 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_pred_bounds[which(as.character(seqnames(all_pred_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[2]][which(as.character(seqnames(annots.GR.f[[2]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

p_to_rad21 <- GenometriCorrelation(all_pred_bounds,
                                      annots.GR.f[[2]], 
                                      chromosomes.length = chromslength,
                                      chromosomes.to.proceed = tolower(chrs),
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_pred_bounds[which(as.character(seqnames(all_pred_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[3]][which(as.character(seqnames(annots.GR.f[[3]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

p_to_smc3a <- GenometriCorrelation(all_pred_bounds,
                                      annots.GR.f[[3]], 
                                      chromosomes.length = chromslength,
                                      chromosomes.to.proceed = tolower(chrs),
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_pred_bounds[which(as.character(seqnames(all_pred_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[4]][which(as.character(seqnames(annots.GR.f[[4]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

p_to_znf143 <- GenometriCorrelation(all_pred_bounds,
                                       annots.GR.f[[4]], 
                                       chromosomes.length = chromslength,
                                       chromosomes.to.proceed = tolower(chrs), 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)

```

### Called

```{r}
chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_true_bounds[which(as.character(seqnames(all_true_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[1]][which(as.character(seqnames(annots.GR.f[[1]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

t_to_ctcf <- GenometriCorrelation(all_true_bounds,
                                     annots.GR.f[[1]], 
                                     chromosomes.length = chromslength,
                                     chromosomes.to.proceed = tolower(chrs), 
                                     permut.number = 100,
                                     ecdf.area.permut.number = 100,
                                     mean.distance.permut.number = 100,
                                     jaccard.measure.permut.number = 100,
                                     keep.distributions = TRUE, 
                                     showProgressBar = TRUE)

chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_true_bounds[which(as.character(seqnames(all_true_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[2]][which(as.character(seqnames(annots.GR.f[[2]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

t_to_rad21 <- GenometriCorrelation(all_true_bounds,
                                      annots.GR.f[[2]], 
                                      chromosomes.length = chromslength,
                                      chromosomes.to.proceed = tolower(chrs),
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_true_bounds[which(as.character(seqnames(all_true_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[3]][which(as.character(seqnames(annots.GR.f[[3]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

t_to_smc3a <- GenometriCorrelation(all_true_bounds,
                                      annots.GR.f[[3]], 
                                      chromosomes.length = chromslength,
                                      chromosomes.to.proceed = tolower(chrs),
                                      permut.number = 100,
                                      ecdf.area.permut.number = 100,
                                      mean.distance.permut.number = 100,
                                      jaccard.measure.permut.number = 100,
                                      keep.distributions = TRUE, 
                                      showProgressBar = TRUE)

chromslength <- numeric()
for(i in 1:length(chrs)){
  chromslength[i] <- max(end(all_true_bounds[which(as.character(seqnames(all_true_bounds))==tolower(chrs[i]))]),
                         end(annots.GR.f[[4]][which(as.character(seqnames(annots.GR.f[[4]]))==tolower(chrs[i]))]))
}
names(chromslength) <- tolower(chrs)

t_to_znf143 <- GenometriCorrelation(all_true_bounds,
                                       annots.GR.f[[4]], 
                                       chromosomes.length = chromslength,
                                       chromosomes.to.proceed = tolower(chrs), 
                                       permut.number = 100,
                                       ecdf.area.permut.number = 100,
                                       mean.distance.permut.number = 100,
                                       jaccard.measure.permut.number = 100,
                                       keep.distributions = TRUE, 
                                       showProgressBar = TRUE)

```

### Plots

```{r}
pred_v_called_10_df <- data.frame(AbsoluteDist = c(#Predicted
  p_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  p_to_rad21@.Data[[1]]$absolute.min.distance.data,
  p_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  p_to_znf143@.Data[[1]]$absolute.min.distance.data,
  
  #Called
  t_to_ctcf@.Data[[1]]$absolute.min.distance.data,
  t_to_rad21@.Data[[1]]$absolute.min.distance.data,
  t_to_smc3a@.Data[[1]]$absolute.min.distance.data,
  t_to_znf143@.Data[[1]]$absolute.min.distance.data
),
Annotation = c(#Predicted
    rep("CTCF",length(p_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(p_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(p_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(p_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #Called
    rep("CTCF",length(t_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("RAD21",length(t_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("SMC3a",length(t_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("ZNF143",length(t_to_znf143@.Data[[1]]$absolute.min.distance.data))),
BoundReg = c(#Predicted
    rep("Predicted", length(p_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("Predicted", length(p_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("Predicted", length(p_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("Predicted", length(p_to_znf143@.Data[[1]]$absolute.min.distance.data)),
    
    #Called
    rep("Called", length(t_to_ctcf@.Data[[1]]$absolute.min.distance.data)),
    rep("Called", length(t_to_rad21@.Data[[1]]$absolute.min.distance.data)),
    rep("Called", length(t_to_smc3a@.Data[[1]]$absolute.min.distance.data)),
    rep("Called", length(t_to_znf143@.Data[[1]]$absolute.min.distance.data))))
    
pred_v_called_10_df$BoundReg <- factor(pred_v_called_10_df$BoundReg, levels=c("Predicted", "Called"))
pred_v_called_10_df$log2AbsoluteDist <- log(pred_v_called_10_df$AbsoluteDist + 1, base = 2)

ggplot(pred_v_called_10_df, aes(x=BoundReg, y = log2AbsoluteDist, fill=BoundReg))  + 
  facet_grid(~ Annotation) +    
  stat_boxplot(geom ='errorbar', width = 0.2) + 
  geom_boxplot(outlier.shape = NA) +
  geom_signif(test = "wilcox.test", 
              comparisons = list( c("Predicted", "Called")),
              vjust = 0,
              textsize = 4,
              size = .5,
              step_increase = .08) +
  theme_minimal()+
  theme_bw()+
  ylab("Log2 Distance to Annotation")+
  xlab("") +
  scale_fill_discrete(name="Boundary Region")+
  #guides(color=FALSE, linetype=FALSE)+
  theme(axis.text.x = element_text(size=15,
                                   angle = 45,
                                   hjust = 1),
        axis.text.y = element_text(size = 15),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        strip.text.x = element_text(size = 15),
        #panel.spacing = unit(2, "lines"),
        legend.text=element_text(size=15),
        legend.title=element_text(size=20),
        plot.title = element_text(size=20),
        legend.position = "bottom")

```

