---
title: "Evaluating Model Performances"
subtitle: "RF; no enet"
author: "Spiro Stilianoudakis"
date: "March 8, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)

```

# GM12878

##5kb

```{r}
mccdata_gm12878_5kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/GM12878/5kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/5kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_gm12878_5kb <- rbind(mccdata_gm12878_5kb,
										  perfdata[15,2])
		}
	}
}


```

##10kb

```{r}
mccdata_gm12878_10kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_gm12878_10kb <- rbind(mccdata_gm12878_10kb,
										  perfdata[15,2])
		}
	}
}


```

##25kb

```{r}
mccdata_gm12878_25kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/GM12878/25kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/25kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_gm12878_25kb <- rbind(mccdata_gm12878_25kb,
										  perfdata[15,2])
		}
	}
}

```

##50kb

```{r}
mccdata_gm12878_50kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/GM12878/50kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/50kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_gm12878_50kb <- rbind(mccdata_gm12878_50kb,
										  perfdata[15,2])
		}
	}
}


```

##100kb

```{r}
mccdata_gm12878_100kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/GM12878/100kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/100kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_gm12878_100kb <- rbind(mccdata_gm12878_100kb,
										  perfdata[15,2])
		}
	}
}


```

# K562

##5kb

```{r}
mccdata_K562_5kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
		  files <- list.files(paste0("Z:/TAD_data_analysis/K562/5kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/K562/5kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
		  
		  mccdata_K562_5kb <- rbind(mccdata_K562_5kb,
										  perfdata[15,2])
			
		}
	}
}


```

##10kb

```{r}
mccdata_K562_10kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
		  files <- list.files(paste0("Z:/TAD_data_analysis/K562/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/K562/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
		  
		  mccdata_K562_10kb <- rbind(mccdata_K562_10kb,
										  perfdata[15,2])
			
		}
	}
}


```

##25kb

```{r}
mccdata_K562_25kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/K562/25kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/K562/25kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_K562_25kb <- rbind(mccdata_K562_25kb,
										  perfdata[15,2])
		}
	}
}

```

##50kb

```{r}
mccdata_K562_50kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/K562/50kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/K562/50kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_K562_50kb <- rbind(mccdata_K562_50kb,
										  perfdata[15,2])
		}
	}
}


```

##100kb

```{r}
mccdata_K562_100kb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			files <- list.files(paste0("Z:/TAD_data_analysis/K562/100kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet"))
		  if("rfperf_noenet.rds" %in% files){
		    perfdata <- readRDS(paste0("Z:/TAD_data_analysis/K562/100kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
		  }else{perfdata=data.frame(Metric = c("TN",
                                "FN",
                                "FP",
                                "TP",
                                "Total",
                                "Sensitivity",
                                "Specificity",
                                "Kappa",
                                "Accuracy",
                                "Precision",
                                "FPR",
                                "FNR",
                                "FOR",
                                "NPV",
                                "MCC",
                                "F1",
                                "AUC",
                                "Youden",
                                "AUPRC"), 
                     Performance=NA)}
									   
			mccdata_K562_100kb <- rbind(mccdata_K562_100kb,
										  perfdata[15,2])
		}
	}
}


```


# Line Plots V1

```{r}
all_rfperfs <- rbind.data.frame(mccdata_gm12878_5kb,
                                mccdata_gm12878_10kb,
                                mccdata_gm12878_25kb,
                                mccdata_gm12878_50kb,
                                mccdata_gm12878_100kb,
                                mccdata_K562_5kb,
                                mccdata_K562_10kb,
                                mccdata_K562_25kb,
                                mccdata_K562_50kb,
                                mccdata_K562_100kb)
all_rfperfs$CL <- c(rep("GM12878", length(mccdata_gm12878_10kb)*5), rep("K562", length(mccdata_K562_10kb)*5))
all_rfperfs$Resolution <- rep(c(rep("5 kb", length(mccdata_gm12878_5kb)),
                            rep("10 kb", length(mccdata_gm12878_10kb)),
                            rep("25 kb", length(mccdata_gm12878_25kb)),
                            rep("50 kb", length(mccdata_gm12878_50kb)),
                            rep("100 kb", length(mccdata_gm12878_100kb))), 2)
all_rfperfs$Resampling <- rep(c(rep("None", 3),
                            rep("ROS", 3),
                            rep("RUS", 3),
                            rep("SMOTE", 3)),210)
all_rfperfs$Predictor <- rep(c("Distance", "OC", "OP"), 840)
all_rfperfs$Chromosome <- c(rep("CHR1", 12),
                            rep("CHR2", 12),
                            rep("CHR3", 12),
                            rep("CHR4", 12),
                            rep("CHR5", 12),
                            rep("CHR6", 12),
                            rep("CHR7", 12),
                            rep("CHR8", 12),
                            rep("CHR10", 12),
                            rep("CHR11", 12),
                            rep("CHR12", 12),
                            rep("CHR13", 12),
                            rep("CHR14", 12),
                            rep("CHR15", 12),
                            rep("CHR16", 12),
                            rep("CHR17", 12),
                            rep("CHR18", 12),
                            rep("CHR19", 12),
                            rep("CHR20", 12),
                            rep("CHR21", 12),
                            rep("CHR22", 12))

all_rfperfs$CL <- factor(all_rfperfs$CL, levels = c("GM12878", "K562"))
all_rfperfs$Resolution <- factor(all_rfperfs$Resolution, levels = c("5 kb", "10 kb", "25 kb", "50 kb", "100 kb"))
all_rfperfs$Resampling <- factor(all_rfperfs$Resampling, levels = c("None", "ROS", "RUS", "SMOTE"))
all_rfperfs$Predictor <- factor(all_rfperfs$Predictor, levels = c("OC", "OP", "Distance"))
all_rfperfs$Chromosome <- factor(all_rfperfs$Chromosome, levels = paste0("CHR", c(1:8,10:22)))

all_rfperfs_mcc <- all_rfperfs %>%
  dplyr::group_by(CL, Resolution, Resampling, Predictor) %>%
  dplyr::summarise(MCC = mean(V1, na.rm = TRUE),
            MCCSD = sd(V1, na.rm = TRUE))

#GM12878
c <- ggplot(all_rfperfs_mcc[which(all_rfperfs_mcc$CL=="GM12878" & all_rfperfs_mcc$Predictor=="OC"),], aes(x=Resolution, y=MCC, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
                 position=position_dodge(0.5)) +
     #facet_grid(~ Metric)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + ylim(-.1,.5) +
     ggtitle("Overlap Counts") +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

p <- ggplot(all_rfperfs_mcc[which(all_rfperfs_mcc$CL=="GM12878" & all_rfperfs_mcc$Predictor=="OP"),], aes(x=Resolution, y=MCC, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
                 position=position_dodge(0.5)) +
     #facet_grid(~ Metric)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + ylim(-.1,.5) +
     ggtitle("Overlap Percents") +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

d <- ggplot(all_rfperfs_mcc[which(all_rfperfs_mcc$CL=="GM12878" & all_rfperfs_mcc$Predictor=="Distance"),], aes(x=Resolution, y=MCC, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
                 position=position_dodge(0.5)) +
     #facet_grid(~ Metric)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + ylim(-.1,.5) +
     ggtitle("Distance") +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

figure <- ggarrange(c,p,d,
                ncol = 3, nrow = 1, 
                common.legend = TRUE, 
                legend = "top",
                labels = "AUTO",
                font.label = list(size=20))
figure
annotate_figure(figure,
    bottom = text_grob("Resolution", color = "black", size = 20),
    left = text_grob("MCC", color = "black", rot = 90, size=20)
)


#K562
c2 <- ggplot(all_rfperfs_mcc[which(all_rfperfs_mcc$CL=="K562" & all_rfperfs_mcc$Predictor=="OC"),], aes(x=Resolution, y=MCC, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
                 position=position_dodge(0.5)) +
     #facet_grid(~ Metric)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + ylim(-.1,.5) +
     ggtitle("Overlap Counts") +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

p2 <- ggplot(all_rfperfs_mcc[which(all_rfperfs_mcc$CL=="K562" & all_rfperfs_mcc$Predictor=="OP"),], aes(x=Resolution, y=MCC, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
                 position=position_dodge(0.5)) +
     #facet_grid(~ Metric)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + ylim(-.1,.5) +
     ggtitle("Overlap Percents") +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

d2 <- ggplot(all_rfperfs_mcc[which(all_rfperfs_mcc$CL=="K562" & all_rfperfs_mcc$Predictor=="Distance"),], aes(x=Resolution, y=MCC, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
                 position=position_dodge(0.5)) +
     #facet_grid(~ Metric)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + ylim(-.1,.5) +
     ggtitle("Distance") +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

figure2 <- ggarrange(c2,p2,d2,
                ncol = 3, nrow = 1, 
                common.legend = TRUE, 
                legend = "top",
                labels = "AUTO",
                font.label = list(size=20))
figure2
annotate_figure(figure2,
    bottom = text_grob("Resolution", color = "black", size = 20),
    left = text_grob("MCC", color = "black", rot = 90, size=20)
)

```

# Line Plots V2

```{r}
x <- ggplot(all_rfperfs_mcc, aes(x=Resolution, y=MCC, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(CL ~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("Resolution") + ylab("MCC") + ylim(-.1,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     strip.text.x = element_text(size = 15),
     strip.text.y = element_text(size = 15),
     panel.spacing = unit(2, "lines"),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20),
     legend.position="bottom")

#figure <- ggarrange(x,
#                ncol = 1, nrow = 1, 
#                common.legend = TRUE, 
#                legend = "bottom")
#figure
#annotate_figure(figure,
#    bottom = text_grob("Resolution", color = "black", size = 20),
#    left = text_grob("MCC", color = "black", rot = 90, size=20)
#)

```


