---
title: "evaluating_model_performances_xgboost"
author: "Spiro Stilianoudakis"
date: "May 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)

```

# GM12878

##10kb

###MCC

####RF; No elastic-net

```{r}
mccdata_gm12878_10kb_rf <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
									   
			mccdata_gm12878_10kb_rf <- rbind(mccdata_gm12878_10kb_rf,
										  perfdata[15,2])
		}
	}
}


```

####XGB; no elastic-net

```{r}
mccdata_gm12878_10kb_xgb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/gbmperf_noenet.rds"))
									   
			mccdata_gm12878_10kb_xgb <- rbind(mccdata_gm12878_10kb_xgb,
										  perfdata[15,2])
		}
	}
}


```

###Plots

```{r}
all_rfperfs <- rbind.data.frame(mccdata_gm12878_10kb_rf,
                                mccdata_gm12878_10kb_xgb)

all_rfperfs$Model <- c(rep("RF", length(mccdata_gm12878_10kb_rf)),
                                rep("XGB", length(mccdata_gm12878_10kb_xgb)))
all_rfperfs$Predictor <- rep(c("Distance", "OC", "OP"), 168)
all_rfperfs$Resampling <- rep(c(rep("None", 3),
                            rep("ROS", 3),
                            rep("RUS", 3),
                            rep("SMOTE", 3)),42)
all_rfperfs$Chromosome <- rep(c(rep("CHR1", 12),
                            rep("CHR2", 12),
                            rep("CHR3", 12),
                            rep("CHR4", 12),
                            rep("CHR5", 12),
                            rep("CHR6", 12),
                            rep("CHR7", 12),
                            rep("CHR8", 12),
                            rep("CHR10", 12),
                            rep("CHR11", 12),
                            rep("CHR12", 12),
                            rep("CHR13", 12),
                            rep("CHR14", 12),
                            rep("CHR15", 12),
                            rep("CHR16", 12),
                            rep("CHR17", 12),
                            rep("CHR18", 12),
                            rep("CHR19", 12),
                            rep("CHR20", 12),
                            rep("CHR21", 12),
                            rep("CHR22", 12)), 2)

all_rfperfs$Resampling <- factor(all_rfperfs$Resampling, levels = c("None", "ROS", "RUS", "SMOTE"))
all_rfperfs$Predictor <- factor(all_rfperfs$Predictor, levels = c("OC", "OP", "Distance"))
all_rfperfs$Chromosome <- factor(all_rfperfs$Chromosome, levels = paste0("CHR", c(1:8,10:22)))

all_rfperfs_mcc <- all_rfperfs %>%
  dplyr::group_by(Model, Resampling, Predictor) %>%
  dplyr::summarise(MCC = mean(V1, na.rm = TRUE),
            MCCSD = sd(V1, na.rm = TRUE))

ggplot(all_rfperfs_mcc, aes(x=Predictor, y=MCC, fill=Model)) +
     #geom_line(size=2, position=position_dodge(0.5))+
     #geom_point(size=5, position=position_dodge(0.5))+
     #geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=1,
     #             position=position_dodge(0.5)) +
     geom_bar(position=position_dodge(), stat="identity", colour='black') +
     geom_errorbar(aes(ymin=MCC-MCCSD, ymax=MCC+MCCSD), width=.5,position=position_dodge(.9)) +
     facet_grid(~ Resampling)+
     theme_minimal() +
     theme_bw()+
     #xlab("") + ylab("") + ylim(-.05,.5) +
     scale_color_discrete(name="Predictor Type")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

```

###F1

####RF; No elastic-net

```{r}
F1data_gm12878_10kb_rf <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/rfperf_noenet.rds"))
									   
			F1data_gm12878_10kb_rf <- rbind(F1data_gm12878_10kb_rf,
										  perfdata[16,2])
		}
	}
}


```

####XGB; no elastic-net

```{r}
F1data_gm12878_10kb_xgb <- numeric()

for(i in paste0("CHR", c(1:8,10:22))){
	for(j in c("none","ros","rus","smote")){
		for(k in c("distance", "oc", "op")){
			perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/10kb/results_by_chr/",
									   i, 
									   "/",
									   j, 
									   "/", 
									   k, 
									   "/enet/gbmperf_noenet.rds"))
									   
			F1data_gm12878_10kb_xgb <- rbind(F1data_gm12878_10kb_xgb,
										  perfdata[16,2])
		}
	}
}


```

###Plots

```{r}
all_rfperfs <- rbind.data.frame(F1data_gm12878_10kb_rf,
                                F1data_gm12878_10kb_xgb)

all_rfperfs$Model <- c(rep("RF", length(F1data_gm12878_10kb_rf)),
                                rep("XGB", length(F1data_gm12878_10kb_xgb)))
all_rfperfs$Predictor <- rep(c("Distance", "OC", "OP"), 168)
all_rfperfs$Resampling <- rep(c(rep("None", 3),
                            rep("ROS", 3),
                            rep("RUS", 3),
                            rep("SMOTE", 3)),42)
all_rfperfs$Chromosome <- rep(c(rep("CHR1", 12),
                            rep("CHR2", 12),
                            rep("CHR3", 12),
                            rep("CHR4", 12),
                            rep("CHR5", 12),
                            rep("CHR6", 12),
                            rep("CHR7", 12),
                            rep("CHR8", 12),
                            rep("CHR10", 12),
                            rep("CHR11", 12),
                            rep("CHR12", 12),
                            rep("CHR13", 12),
                            rep("CHR14", 12),
                            rep("CHR15", 12),
                            rep("CHR16", 12),
                            rep("CHR17", 12),
                            rep("CHR18", 12),
                            rep("CHR19", 12),
                            rep("CHR20", 12),
                            rep("CHR21", 12),
                            rep("CHR22", 12)), 2)

all_rfperfs$Resampling <- factor(all_rfperfs$Resampling, levels = c("None", "ROS", "RUS", "SMOTE"))
all_rfperfs$Predictor <- factor(all_rfperfs$Predictor, levels = c("OC", "OP", "Distance"))
all_rfperfs$Chromosome <- factor(all_rfperfs$Chromosome, levels = paste0("CHR", c(1:8,10:22)))

all_rfperfs_F1 <- all_rfperfs %>%
  dplyr::group_by(Model, Resampling, Predictor) %>%
  dplyr::summarise(F1 = mean(V1, na.rm = TRUE),
            F1SD = sd(V1, na.rm = TRUE))

ggplot(all_rfperfs_F1, aes(x=Predictor, y=F1, fill=Model)) +
     #geom_line(size=2, position=position_dodge(0.5))+
     #geom_point(size=5, position=position_dodge(0.5))+
     #geom_errorbar(aes(ymin=F1-F1SD, ymax=F1+F1SD), width=1,
     #             position=position_dodge(0.5)) +
     geom_bar(position=position_dodge(), stat="identity", colour='black') +
     geom_errorbar(aes(ymin=F1-F1SD, ymax=F1+F1SD), width=.5,position=position_dodge(.9)) +
     facet_grid(~ Resampling)+
     theme_minimal() +
     theme_bw()+
     #xlab("") + ylab("") + ylim(-.05,.5) +
     scale_color_discrete(name="Predictor Type")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

```
