---
title: "Evaluating Preprocessed TAD Summaries"
author: "Spiro Stilianoudakis"
date: "July 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(plyr)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
#library(leaps)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)

```

# GM12878

```{r}

num_domains <- numeric()
num_domains_lt_2mb <- numeric()
num_domains2 <- numeric()
num_domains_gt_res <- numeric()
num_domains3 <- numeric()
num_bounds <- numeric()

res <- c("5kb" ,"10kb", "25kb","50kb", "100kb")
for(i in 1:length(res)){
  domains <- read.table(paste0("Z:/TAD_data_analysis/GM12878/",
                               res[i],
                               "/GM12878_domain_data_",
                               as.integer(gsub("kb", "000", res[i])),
                               ".b.txt"), header=F)
  domains <- domains[,1:3]
  names(domains) <- c("Chromosome","Start","End")
  
  num_domains <- rbind(num_domains, nrow(domains))
  num_domains_lt_2mb <- rbind(num_domains_lt_2mb,length(which((domains$End - domains$Start)>=2000000)))
  
  domains2 <- domains[which((domains$End - domains$Start)<2000000),]
  
  num_domains2 <- rbind(num_domains2, nrow(domains2))
  num_domains_gt_res <- rbind(num_domains_gt_res, length(which((domains2$End - domains2$Start)<=(as.integer(gsub("kb", "000", res[i]))))))
  
  domains3 <- domains2[which((domains2$End - domains2$Start)>(as.integer(gsub("kb", "000", res[i])))),]
  
  num_domains3 <- rbind(num_domains3, nrow(domains3))
  
  bounds <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/",
                           res[i],
                           "/training_testing/bounds.rds"))
  
  num_bounds <- rbind(num_bounds, length(bounds))
}

tad_sum_df_gm12878 <- cbind(c("5kb" ,"10kb", "25kb","50kb", "100kb"),
                    num_domains,
                    num_domains_lt_2mb,
                    num_domains2,
                    num_domains_gt_res,
                    num_domains3,
                    num_bounds)

```

# K562

```{r}

num_domains <- numeric()
num_domains_lt_2mb <- numeric()
num_domains2 <- numeric()
num_domains_gt_res <- numeric()
num_domains3 <- numeric()
num_bounds <- numeric()

res <- c("5kb" ,"10kb", "25kb","50kb", "100kb")
for(i in 1:length(res)){
  domains <- read.table(paste0("Z:/TAD_data_analysis/K562/",
                               res[i],
                               "/K562_domain_data_",
                               as.integer(gsub("kb", "000", res[i])),
                               ".b.txt"), header=F)
  domains <- domains[,1:3]
  names(domains) <- c("Chromosome","Start","End")
  
  num_domains <- rbind(num_domains, nrow(domains))
  num_domains_lt_2mb <- rbind(num_domains_lt_2mb,length(which((domains$End - domains$Start)>=2000000)))
  
  domains2 <- domains[which((domains$End - domains$Start)<2000000),]
  
  num_domains2 <- rbind(num_domains2, nrow(domains2))
  num_domains_gt_res <- rbind(num_domains_gt_res, length(which((domains2$End - domains2$Start)<=(as.integer(gsub("kb", "000", res[i]))))))
  
  domains3 <- domains2[which((domains2$End - domains2$Start)>(as.integer(gsub("kb", "000", res[i])))),]
  
  num_domains3 <- rbind(num_domains3, nrow(domains3))
  
  bounds <- readRDS(paste0("Z:/TAD_data_analysis/K562/",
                           res[i],
                           "/training_testing/bounds.rds"))
  
  num_bounds <- rbind(num_bounds, length(bounds))
}

tad_sum_df_k562 <- cbind(c("5kb" ,"10kb", "25kb","50kb", "100kb"),
                    num_domains,
                    num_domains_lt_2mb,
                    num_domains2,
                    num_domains_gt_res,
                    num_domains3,
                    num_bounds)

```