---
title: "evaluating_enet_penalization_parameters"
author: "Spiro Stilianoudakis"
date: "May 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Using AUPRC as CV metric

## Alpha: 0-1 length 100
## Lambda: 0-10 length 100

### GM12878

```{r}
alpha.per.chr <- numeric()
lambda.per.chr <- numeric()
chr.per.chr <- character()
res.per.chr <- character()
samp.per.chr <- character()
pred.per.chr <- character()


for(i in c("10kb", "25kb","50kb","100kb")){
  for(j in paste0("CHR", c(1:8,10:22))){
	  for(k in c("none","ros","rus","smote")){
		  for(l in c("distance", "oc", "op")){
		    print(paste(i, j, k, l))
			  enetmodel <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/",
			               i,
                     "/results_by_chr/",
									   j, 
									   "/",
									   k, 
									   "/", 
									   l, 
									   "/enet/eNetModel.rds"))
			  
			  res.per.chr <- rbind(res.per.chr, i)
			  chr.per.chr <- rbind(chr.per.chr, j)
			  samp.per.chr <- rbind(samp.per.chr, k)
			  pred.per.chr <- rbind(pred.per.chr, l)
			  
			  alpha.per.chr <- rbind(alpha.per.chr, as.numeric(enetmodel$bestTune[1])) 
        lambda.per.chr <- rbind(lambda.per.chr, as.numeric(enetmodel$bestTune[2])) 
		  }
	  }
  }
}

penal_params_gm12878 <- cbind.data.frame(Resolution = res.per.chr,
                                         CHR = chr.per.chr,
                                         Resampling = samp.per.chr,
                                         Predictor = pred.per.chr,
                                         Alpha = alpha.per.chr,
                                         Lambda = lambda.per.chr)

penal_params_gm12878$Resolution <- factor(penal_params_gm12878$Resolution, levels=c("10kb", "25kb", "50kb", "100kb"))
penal_params_gm12878$Predictor <- factor(penal_params_gm12878$Predictor, levels=c("oc","op","distance"))

penal_params_gm12878_summ <- penal_params_gm12878 %>%
  dplyr::group_by(Resolution, Resampling, Predictor) %>%
  dplyr::summarise(alpha = mean(Alpha, na.rm = TRUE),
            alphaSD = sd(Alpha, na.rm = TRUE),
            lambda = mean(Lambda, na.rm = TRUE),
            lambdaSD = sd(Lambda, na.rm = TRUE))

saveRDS(penal_params_gm12878_summ, "/home/stilianoudakisc/TAD_data_analysis/evaluating_alpha_and_lambda/penal_params_gm12878_summ.rds")	
```

### Plots 

```{r}
penal_params_gm12878 <- readRDS("Z:/TAD_data_analysis/evaluating_alpha_and_lambda/penal_params_gm12878.rds")

penal_params_gm12878_summ <- penal_params_gm12878 %>%
  group_by(Resolution, Resampling, Predictor) %>%
  summarise(alpha = mean(Alpha, na.rm = TRUE),
            alphaSD = sd(Alpha, na.rm = TRUE),
            lambda = mean(Lambda, na.rm = TRUE),
            lambdaSD = sd(Lambda, na.rm = TRUE))

#alpha
alphaplot <- ggplot(penal_params_gm12878_summ, aes(x=Resolution, y=alpha, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=alpha-alphaSD, ymax=alpha+alphaSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     #xlab("") + ylab("") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#lambda
lambdaplot <- ggplot(penal_params_gm12878_summ, aes(x=Resolution, y=lambda, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=lambda-lambdaSD, ymax=lambda+lambdaSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     #xlab("") + ylab("") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

figure <- ggarrange(alphaplot,
                    lambdaplot,
                    ncol = 1,
                    nrow = 2,
                    common.legend = TRUE,
                    legend = "top")
figure
```


### K562

```{r}
alpha.per.chr <- numeric()
lambda.per.chr <- numeric()
chr.per.chr <- character()
res.per.chr <- character()
samp.per.chr <- character()
pred.per.chr <- character()


for(i in c("10kb", "25kb","50kb","100kb")){
  for(j in paste0("CHR", c(1:8,10:22))){
	  for(k in c("none","ros","rus","smote")){
		  for(l in c("distance", "oc", "op")){
		    print(paste(i, j, k, l))
			  enetmodel <- readRDS(paste0("Z:/TAD_data_analysis/K562/",
			               i,
                     "/results_by_chr/",
									   j, 
									   "/",
									   k, 
									   "/", 
									   l, 
									   "/enet/eNetModel.rds"))
			  
			  res.per.chr <- rbind(res.per.chr, i)
			  chr.per.chr <- rbind(chr.per.chr, j)
			  samp.per.chr <- rbind(samp.per.chr, k)
			  pred.per.chr <- rbind(pred.per.chr, l)
			  
			  alpha.per.chr <- rbind(alpha.per.chr, as.numeric(enetmodel$bestTune[1])) 
        lambda.per.chr <- rbind(lambda.per.chr, as.numeric(enetmodel$bestTune[2])) 
		  }
	  }
  }
}

penal_params_K562 <- cbind.data.frame(Resolution = res.per.chr,
                                         CHR = chr.per.chr,
                                         Resampling = samp.per.chr,
                                         Predictor = pred.per.chr,
                                         Alpha = alpha.per.chr,
                                         Lambda = lambda.per.chr)

penal_params_K562$Resolution <- factor(penal_params_K562$Resolution, levels=c("10kb", "25kb", "50kb", "100kb"))
penal_params_K562$Predictor <- factor(penal_params_K562$Predictor, levels=c("oc","op","distance"))

penal_params_K562_summ <- penal_params_K562 %>%
  dplyr::group_by(Resolution, Resampling, Predictor) %>%
  dplyr::summarise(alpha = mean(Alpha, na.rm = TRUE),
            alphaSD = sd(Alpha, na.rm = TRUE),
            lambda = mean(Lambda, na.rm = TRUE),
            lambdaSD = sd(Lambda, na.rm = TRUE))

saveRDS(penal_params_K562_summ, "/home/stilianoudakisc/TAD_data_analysis/evaluating_alpha_and_lambda/penal_params_K562_summ.rds")	
```

### Plots 

```{r}
penal_params_K562 <- readRDS("Z:/TAD_data_analysis/evaluating_alpha_and_lambda/penal_params_K562.rds")

penal_params_K562_summ <- penal_params_K562 %>%
  group_by(Resolution, Resampling, Predictor) %>%
  summarise(alpha = mean(Alpha, na.rm = TRUE),
            alphaSD = sd(Alpha, na.rm = TRUE),
            lambda = mean(Lambda, na.rm = TRUE),
            lambdaSD = sd(Lambda, na.rm = TRUE))

#alpha
ggplot(penal_params_K562_summ, aes(x=Resolution, y=alpha, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=alpha-alphaSD, ymax=alpha+alphaSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#lambda
ggplot(penal_params_K562_summ, aes(x=Resolution, y=lambda, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=lambda-lambdaSD, ymax=lambda+lambdaSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))
```

