---
title: "investigating_auprc"
author: "Spiro Stilianoudakis"
date: "May 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}
library(GenomicRanges)
library(caret)
library(data.table)
library(gbm)
library(randomForest)
library(glmnet)
library(pROC)
library(dplyr)
library(ggplot2)
library(DMwR)
library(gridExtra)
library(pROC)
library(ROCR)
library(cluster)
library(ggpubr)
library(scales)
library(GGally)
library(VennDiagram)
library(network)
library(sna)
library(gtable)
library(grid)
library(magrittr) 
library(DT)
library(tidyverse)
library(reshape)
library(ROSE)
library(lattice)
library(corrplot)
library(cluster)
library(RColorBrewer)

```

# Investigating Area Under the Precision-Recall Curve

## GM12878

```{r}
auprcdata_gm12878 <- numeric()
pdata_gm12878 <- numeric()
rdata_gm12878 <- numeric()
f1data_gm12878 <- numeric()
tpdata_gm12878 <- numeric()
fpdata_gm12878 <- numeric()
tndata_gm12878 <- numeric()
fndata_gm12878 <- numeric()

for(i in c("10kb", "25kb","50kb","100kb")){
  for(j in paste0("CHR", c(1:8,10:22))){
	  for(k in c("none","ros","rus","smote")){
		  for(l in c("distance", "oc", "op")){
			  perfdata <- readRDS(paste0("Z:/TAD_data_analysis/GM12878/",
			               i,
                     "/results_by_chr/",
									   j, 
									   "/",
									   k, 
									   "/", 
									   l, 
									   "/enet/rfperf.rds"))
			  
			  tndata_gm12878 <- rbind(tndata_gm12878, 
			                          perfdata[1,2])
			  
			  fndata_gm12878 <- rbind(fndata_gm12878, 
			                          perfdata[2,2])
			  
			  fpdata_gm12878 <- rbind(fpdata_gm12878, 
			                          perfdata[3,2])
			  
			  tpdata_gm12878 <- rbind(tpdata_gm12878, 
			                          perfdata[4,2])
									   
			  auprcdata_gm12878 <- rbind(auprcdata_gm12878,
			                             perfdata[19,2])
			  
			  pdata_gm12878 <- rbind(pdata_gm12878,
			                             perfdata[10,2])
			  
			  rdata_gm12878 <- rbind(rdata_gm12878,
			                             perfdata[6,2])
			  
			  f1data_gm12878 <- rbind(f1data_gm12878,
			                             perfdata[16,2])
		  }
	  }
  }
}

pr_results_gm12878 <- cbind.data.frame(TN=tndata_gm12878,
                                       FN=fndata_gm12878,
                                       FP=fpdata_gm12878,
                                       TP=tpdata_gm12878,
                                       AUPRC=auprcdata_gm12878,
                                       Precision=pdata_gm12878,
                                       Recall=rdata_gm12878,
                                       F1=f1data_gm12878,
                                       Predictor=rep(c("Distance", "OC", "OP"), 336),
                                       Resampling=rep(c(rep("None",3),
                                                    rep("ROS", 3),
                                                    rep("RUS", 3),
                                                    rep("SMOTE", 3)),84),
                                       Chromosome=rep(c(rep("CHR1",12),
                                                     rep("CHR2",12),
                                                     rep("CHR3",12),
                                                     rep("CHR4",12),
                                                     rep("CHR5",12),
                                                     rep("CHR6",12),
                                                     rep("CHR7",12),
                                                     rep("CHR8",12),
                                                     rep("CHR10",12),
                                                     rep("CHR11",12),
                                                     rep("CHR12",12),
                                                     rep("CHR13",12),
                                                     rep("CHR14",12),
                                                     rep("CHR15",12),
                                                     rep("CHR16",12),
                                                     rep("CHR17",12),
                                                     rep("CHR18",12),
                                                     rep("CHR19",12),
                                                     rep("CHR20",12),
                                                     rep("CHR21",12),
                                                     rep("CHR22",12)),4),
                                       Resolution=c(rep("10 kb", 21*12),
                                                     rep("25 kb", 21*12),
                                                     rep("50 kb", 21*12),
                                                     rep("100 kb", 21*12)))

pr_results_gm12878$Resolution <- factor(pr_results_gm12878$Resolution, levels=c("10 kb", "25 kb", "50 kb", "100 kb"))
pr_results_gm12878$Predictor <- factor(pr_results_gm12878$Predictor, levels=c("OC","OP","Distance"))

pr_results_gm12878_summ <- pr_results_gm12878 %>%
  dplyr::group_by(Resolution, Resampling, Predictor) %>%
  dplyr::summarise(auprc = mean(AUPRC, na.rm = TRUE),
            auprcSD = sd(AUPRC, na.rm = TRUE),
            precision = mean(Precision, na.rm = TRUE),
            precisionSD = sd(Precision, na.rm = TRUE),
            recall = mean(Recall, na.rm = TRUE),
            recallSD = sd(Recall, na.rm = TRUE),
            f1 = mean(F1, na.rm = TRUE),
            f1SD = sd(F1, na.rm = TRUE),
            tn = mean(TN, na.rm = TRUE),
            tnSD = sd(TN, na.rm = TRUE),
            fn = mean(FN, na.rm = TRUE),
            fnSD = sd(FN, na.rm = TRUE),
            fp = mean(FP, na.rm = TRUE),
            fpSD = sd(FP, na.rm = TRUE),
            tp = mean(TP, na.rm = TRUE),
            tpSD = sd(TP, na.rm = TRUE))

#auprc
auprcplot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=auprc, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=auprc-auprcSD, ymax=auprc+auprcSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("AUPRC") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#precision
precisionplot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=precision, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=precision-precisionSD, ymax=precision+precisionSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("Precision") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#recall
recallplot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=recall, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=recall-recallSD, ymax=recall+recallSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("Recall") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#f1
f1plot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=f1, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=f1-f1SD, ymax=f1+f1SD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("F1") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#TP
tpplot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=tp, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=tp-tpSD, ymax=tp+tpSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("True Positives") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#FP
fpplot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=fp, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=fp-fpSD, ymax=fp+fpSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("False Positives") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#TN
tnplot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=tn, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=tn-tnSD, ymax=tn+tnSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("True Negatives") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))

#FN
fnplot <- ggplot(pr_results_gm12878_summ, aes(x=Resolution, y=fn, color=Resampling, group=Resampling)) +
     geom_line(size=2, position=position_dodge(0.5))+
     geom_point(size=5, position=position_dodge(0.5))+
     geom_errorbar(aes(ymin=fn-fnSD, ymax=fn+fnSD), width=1,
                 position=position_dodge(0.5)) +
     facet_grid(~ Predictor)+
     theme_minimal() +
     theme_bw()+
     xlab("") + ylab("False Negatives") + #ylim(-.05,.5) +
     scale_color_discrete(name="Resampling Technique")+
     guides(shape=FALSE, linetype=FALSE)+
     theme(axis.text.x = element_text(size=15,
                                      angle = 45, 
                                      #margin = ggplot2::margin(t = 35),
                                      hjust = 1
     ),
     axis.text.y = element_text(size = 15),
     axis.title.x = element_text(size = 20),
     axis.title.y = element_text(size = 20),
     legend.text=element_text(size=15),
     legend.title=element_text(size=20),
     plot.title = element_text(size=20))
```
